### ISSUE TITLE
`vg autoindex --workflow giraffe` No non-alt-allele paths available in the graph!

### ISSUE THREAD

**Issue by maxrossi91** [vgteam/vg#3562] opened 2022-02-23 20:27 UTC
**1. What were you trying to do?**
Build `giraffe` index using `vg autoindex --workflow giraffe` and align reads.

**3. What actually happened?**

Got an error `error:[vg::get_sequence_dictionary] No non-alt-allele paths available in the graph!`

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
error:[vg::get_sequence_dictionary] No non-alt-allele paths available in the graph!
```

**5. What data and command can the vg dev team use to make the problem happen?**

```console
wget ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz

bcftools query -l ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz | grep "HG00111" -v | head -n 125 > sample_list.txt

bcftools view -v snps,indels -m2 -M2 --min-ac 1 -S sample_list.txt -Oz -o chr21_250.vcf.gz ALL.chr21.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz;

vg autoindex --workflow giraffe --prefix Chr21.250 --ref-fasta Homo_sapiens.GRCh38.dna.chromosome.21.fa --vcf chr21_250.vcf.gz -t 32

vg giraffe -t 1 -d Chr21.250.dist -Z Chr21.250.giraffe.gbz -m Chr21.250.min -f <fastq reads> -o SAM > out.sam
```

The problem appear with any readset.

**6. What does running `vg version` say?**

```
vg version v1.38.0 "Canossa"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by anovak@octagon
```

**Comment by jeizenga** [comment] 2022-02-23 23:20
@adamnovak This looks like the issue of dropped reference paths in the GBZ-based pipelines that you worked on recently. Will this be fixed in an up-to-date VG build?

**Comment by adamnovak** [comment] 2022-03-10 22:04
This definitely sounds like a possible duplicate of #3542. I will see if I can replicate this.

**Comment by adamnovak** [comment] 2022-03-10 22:29
OK, I tried with commit 79b056ada and I can't reproduce this issue, so I thunk it is now fixed.

The binary in https://github.com/vgteam/vg/issues/3595#issuecomment-1064185563 ought to incorporate the fix, as will the next release.

**Closed by adamnovak** 2022-03-10 22:29 UTC
