### ISSUE TITLE
Node not found during vg map

### ISSUE THREAD

**Issue by cistarsa** [vgteam/vg#3204] opened 2021-02-19 18:07 UTC
**1. What were you trying to do?**
Map paired-end fq reads to xg

**2. What did you want to happen?**
Generate a gam file 

**3. What actually happened?**
terminate error 

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
NA
```

**5. What data and command can the vg dev team use to make the problem happen?**
```
# first converted minigraph .gfa -> vg using CI docker suggestion: 
$ docker run -v $(pwd):/data --rm quay.io/vgteam/vg:ci-2785-69b052f68df85d69f80f0ad52f685ef05ac3dc60 vg convert -g /data/CPB_Feb5.gf -v >CPB_Feb5.vg

# the call error occurred in the docker container, so I then used the vg from the step above on the newest vg binaries v 1.30.0 and the issue persisted:
#index = xg
./vg index -x CPB_Feb5_1.30.xg CPB_Feb5.vg

# prune 
./vg prune -r -p -t 32 CPB_Feb5.vg  > CPB_Feb5.pruned.vg

# modify for large bubbles:
./vg mod -X 256 CPB_Feb5.pruned.1.30.vg > mod_CPB_Feb5.pruned.1.30.vg

# index =gcsa
./vg index -g CPB_Feb5_1.30.gcsa mod_CPB_Feb5.pruned.1.30.vg -t 32 -b ./ -p

# map *error*
./vg map -t 16 -x CPB_Feb5_1.30.xg -g CPB_Feb5_1.30.gcsa -i -f CPBWGS_11_R1.fastq.gz -f CPBWGS_11_R2.fastq.gz > CPB_11.gam

# error log:
terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'std::runtime_error'
  what():  Attempted to get handle for node 1055098 not present in graph
terminate called recursively
terminate called recursively
terminate called recursively
  what():  Attempted to get handle for node 4141116 not present in graph
terminate called recursively
terminate called recursively
Segmentation fault (core dumped)

#sizes:
1.3G Feb 18 23:43 mod_CPB_Feb5.pruned.1.30.vg
2.5G Feb 19 06:26 CPB_Feb5_1.30.gcsa
592M Feb 18 23:37 CPB_Feb5_1.30.xg

```

**6. What does running `vg version` say?**

```
1.30.0 Carentino
```

**Comment by jeizenga** [comment] 2021-02-19 18:17
The issue is that you do `vg mod -X` after you do `vg index -x`. Chopping the increases the number of nodes that need IDs, so you need to use new IDs. In pipeline you have here, those new IDs will be in the GCSA2, but not in the XG. Move the `vg mod -X` before `vg index -x` and I think you'll be fine.

**Closed by jeizenga** 2021-02-19 18:17 UTC
