### ISSUE TITLE
`construct_chunk` hits assertion at src/constructor.cpp:781 about last_edit_end != -1

### ISSUE THREAD

**Issue by pengyan19** [vgteam/vg#3745] opened 2022-09-24 09:20 UTC
Hello, when I run the vg, I met a question as follows.

vg: src/constructor.cpp:781: vg::ConstructedChunk vg::Constructor::construct_chunk(std::string, std::string, std::vector<vcflib::Variant>, size_t) const: Assertion `last_edit_end != -1' failed.
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_F3jfFS/stacktrace.txt
Please include the stack trace file in your bug report!

**Comment by adamnovak** [comment] 2022-09-26 15:39
It's stopping here:

https://github.com/vgteam/vg/blob/dba464bcc2076ebdbcb1e18eddc739b20315aeb5/src/constructor.cpp#L779-L781

Which is right after we do this:

https://github.com/vgteam/vg/blob/dba464bcc2076ebdbcb1e18eddc739b20315aeb5/src/constructor.cpp#L771-L777

So, we're collecting together some variants to put in the graph, skipping over the ones we don't like, finishing early if there aren't any variants left, and then asserting that we actually have an end position for the last variant remaining (which we always should, because we already made sure there aren't no variants).

@pengyan19 It looks like you have a VCF and FASTA that vg is interpreting as having variants that don't have ends, or something. It could be that you have SVs that are defined via tags, but the tags don't all agree with each other or with how vg wants to interpret them. If you can share the files we can probably reproduce and fix the bug. Otherwise, we can probably enhance the error message in the next version of vg so it reports information about what variant or variants are confusing it.

**Comment by adamnovak** [comment] 2022-09-28 15:50
OK @pengyan19, I got the data you sent me and I have a fix for this *particular* problem in https://github.com/vgteam/vg/pull/3747

The problem seems to be the second variant in your file, `1       6812    SV2`, which has a REF field and a populated base-level ALT field, and both have the same sequence. `vg construct` had a bug where it would crash if there were variants in a "chunk" of the graph under construction but they didn't actually change anything. My fix changes vg to skip over and warn about variants that don't actually change anything.

But I am not sure that vg skipping over these variants is actually what you want.

It looks like the tags on the variant say that it is actually supposed to be a 2307 bp deletion (`SVLEN=-2307;SVTYPE=DEL`), but if the ALT field is filled in with sequence, vg will ignore the tags even if you pass the `-S` / `--handle-sv` option, because it assumes that the ALT column is correct.

If you want to use the SVLEN and SVTYPE tags instead, you need to remove the ALT column sequence and replace it with a symbolic alt allele value (like `<DEL>` in this case), and then use the `--handle-sv` option to make `vg construct` interpret those tags.

Also, in addition to these variants that don't actually change anything because REF = ALT, there are later variants in your file where REF doesn't match the reference you sent me. For example:

```
error:[vg::Constructor] Variant/reference sequence mismatch: A vs pos: 230949: G; do your VCF and FASTA coordinates match?
Variant: 1	230949	SV96	A ...
```

I think this is the source of your other issue #3744. I suppose we *could* add a way to try and skip over variants that disagree with the reference, but that's an easy way to generate a graph where the variants that *do* match aren't actually placed correctly, and just happened to match the bases at their coordinates. And that graph is going to be worse than useless.

I think you probably have to go back and get the reference that your VCFs are actually called against, and either use that as the basis for your graph, or lift the variants over to the reference you actually want to use in a way that produces a VCF that makes sense.

**Closed** 2022-10-07 20:08 UTC
