### ISSUE TITLE
VG Surject substring position out of range on some GAM records

### ISSUE THREAD

**Issue by cmarkello** [vgteam/vg#2191] opened 2019-03-30 01:21 UTC
@adamnovak @jeizenga @glennhickey 
When running VG Surject using Docker container `quay.io/vgteam/vg:v1.14.0-75-ga72723d3-t291-run` I get the following error on some of the records contained in a GAM that was produced using `vg mpmap` against a chr21 snp1kg graph constructed using the docker container `quay.io/vgteam/vg:v1.14.0-23-g2f02b148-t289-run`. It looks like some expected string mapping positions are not being met by the GAM record.

Input GAM can be found here:
https://storage.googleapis.com/cmarkell-vg-wdl-dev/HG002.ab.gam

Input XG file can be found here:
https://storage.googleapis.com/cmarkell-vg-wdl-dev/snp1kg_maf0.01_chr21.xg

Running `vg surject` command:
```
vg surject -i -x snp1kg_maf0.01_chr21.xg -t 32 -b HG002.ab.gam
```

The following standard error output from that run is as follows:
```
+ vg surject -i -x /cromwell-executions/vgPipeline/c4a68971-276a-4297-a4d1-16f1e0039674/call-runSurject/shard-1/inputs/477995751/snp1kg_maf0.01_chr21.xg -t 32 -b /cromwell-executions/vgPipeline/c4a68971-276a-4297-a4d1-16f1e0039674/call-runSurject/shard-1/inputs/-1449489995/HG002.ab.gam
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 250) > this->size() (which is 247)
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
Stack trace path: /tmp/vg_crash_QO68Li/stacktrace.txt
```

**Comment by adamnovak** [comment] 2019-04-02 00:02
OK, I've got the problem read from the input GAM:

```
{"sequence":"GTTATCCTGGTTGTCATGCCCTTGGACTTTGCCTGGAACTTACACTATTGGCTCTCCTGGTTCCCAGGCCTTCCAAGATGGGCAGGAACTATACCATTTACTCTCCTGAGTCTGCAACTTGCTGACCACAAATCTTGAACTCATCCTCCATAATAGCATGAGCTAATTTATTACAGTAAATCACTTGGTAGAAGATATAGATAGATGATAGATAGATAGATAGATAATAGATAGATAGATAATAGAT","path":{"mapping":[{"position":{"node_id":"3422009","offset":"3","is_reverse":true},"edit":[{"to_length":3,"sequence":"GTT"},{"from_length":26,"to_length":26}],"rank":"1"},{"position":{"node_id":"3422008","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"2"},{"position":{"node_id":"3422006","is_reverse":true},"edit":[{"from_length":23,"to_length":23}],"rank":"3"},{"position":{"node_id":"3422005","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"4"},{"position":{"node_id":"3422003","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"5"},{"position":{"node_id":"3422001","is_reverse":true},"edit":[{"from_length":23,"to_length":23}],"rank":"6"},{"position":{"node_id":"3422000","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"7"},{"position":{"node_id":"3421998","is_reverse":true},"edit":[{"from_length":9,"to_length":9}],"rank":"8"},{"position":{"node_id":"3421996","is_reverse":true},"edit":[{"from_length":11,"to_length":11}],"rank":"9"},{"position":{"node_id":"3421995","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"10"},{"position":{"node_id":"3421994","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"11"},{"position":{"node_id":"3421992","is_reverse":true},"edit":[{"from_length":19,"to_length":19}],"rank":"12"},{"position":{"node_id":"3421991","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"13"},{"position":{"node_id":"3421989","is_reverse":true},"edit":[{"from_length":8,"to_length":8}],"rank":"14"},{"position":{"node_id":"3421988","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"15"},{"position":{"node_id":"3421987","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"16"},{"position":{"node_id":"3421985","is_reverse":true},"edit":[{"from_length":4,"to_length":4}],"rank":"17"},{"position":{"node_id":"3421984","is_reverse":true},"edit":[{"from_length":32,"to_length":32}],"rank":"18"},{"position":{"node_id":"3421982","is_reverse":true},"edit":[{"from_length":3}],"rank":"19"},{"position":{"node_id":"3421980","is_reverse":true},"edit":[{"from_length":3}],"rank":"20"},{"position":{"node_id":"3421978","is_reverse":true},"edit":[{"from_length":7}],"rank":"21"},{"position":{"node_id":"3421976","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"22"},{"position":{"node_id":"3421975","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"23"},{"position":{"node_id":"3421973","is_reverse":true},"edit":[{"from_length":2,"to_length":2}],"rank":"24"},{"position":{"node_id":"3421972","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"25"},{"position":{"node_id":"3421971","is_reverse":true},"edit":[{"from_length":1,"to_length":1}],"rank":"26"},{"position":{"node_id":"3421969","is_reverse":true},"edit":[{"from_length":15,"to_length":15}],"rank":"27"}]},"name":"D00360:97:H2YVMBCXX:1:2215:7201:87409/1","quality":"ISMjIyMoKCgnKCgoKCgoKCgnJygoKCgoKCgoKCgoKCgnKCgoJygoKCgoKCcoKCcnKCcoKCgoKCgoJyckJygoKCgoKCcoKCgoKCgoKCgnJygoKCcnJycmKCgnJyQlJygoKCgoJygjJScnKCgnJycoJygoKCcoJycnKCgoJicoJigoJygoKCgoJycoKCgoJyInJygoKCcnHicnKCcoKCcoJCcnIiYkJycmJygnJygnKCgoKCYoJycnJiQlJyciJSIlJygoJygmJygmJyckJycnHicnJigoJyglJCUnJycnJycoJygnJycmJSceHycoJygnJyYkJScnJw==","mapping_quality":60,"score":239,"fragment_prev":{"name":"D00360:97:H2YVMBCXX:1:2215:7201:87409/1"},"identity":0.988,"annotation":{"fragment_length_distribution":"-I 214.913684 -D 29.407777"}}
```

This read is causing `vg surject` problems because it has 247 bp of sequence/quality info, but an alignment that describes a 250 bp mapping:

```
vg view -aj read.gam | jq '(.sequence | length), ([.path.mapping[].edit[].to_length] | add)'
247
250
```

These should match but are off by 3 bases.

I can patch surject to reject cases like this with an error instead of crashing, but the real problem is going to be inside mpmap.

The first node in the (reverse strand) alignment includes a 3 bp softclip that as far as I can tell maps perfectly to the graph and shouldn't have softclipped in the first place. The rest of the alignment looks reasonable to me at first glance, and it ends in the right place given the read sequence.

<img width="809" alt="Screen Shot 2019-04-01 at 4 54 29 PM" src="https://user-images.githubusercontent.com/5062495/55366792-25aae200-549f-11e9-9b81-261da88ab623.png">

@jeizenga What's going on here with mpmap?

**Comment by adamnovak** [comment] 2019-04-02 00:04
Also, I forgot to mention: the read claims to be paired with itself; it lists its own name as the name in `fragment_prev`.

**Comment by cmarkello** [comment] 2019-04-03 22:04
@jeizenga
Inputs for mpmap run:
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/fq_chunk_1.part.ab.fq.gz`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/fq_chunk_2.part.ab.fq.gz`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/snp1kg_maf0.01_chr21.gbwt`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/snp1kg_maf0.01_chr21.gcsa`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/snp1kg_maf0.01_chr21.gcsa.lcp`
`https://storage.googleapis.com/cmarkell-vg-wdl-dev/snp1kg_maf0.01_chr21.xg`

MPMAP command that was run to generate `https://storage.googleapis.com/cmarkell-vg-wdl-dev/HG002.ab.gam`:
```
vg mpmap \
  -S \
  -f fq_chunk_1.part.ab.fq.gz -f fq_chunk_2.part.ab.fq.gz \
  -x snp1kg_maf0.01_chr21.xg \
  -g snp1kg_maf0.01_chr21.gcsa \
  --gbwt-name snp1kg_maf0.01_chr21.gbwt \
  --recombination-penalty 5.0 -t 16 > HG002.ab.gam
```

**Comment by jeizenga** [comment] 2019-04-04 21:04
Okay, I've got this sorted out. The good news that is that it's already fixed in `master`. This was caused by the same underlying problem that I fixed in https://github.com/vgteam/vg/pull/2166. There's also an additional source of weirdness here because of some data issues: `fq_chunk_1.part.ab.fq.gz` and `fq_chunk_2.part.ab.fq.gz` are actually the same file, which has read pairs interleaved.

**Closed by jeizenga** 2019-04-04 21:04 UTC
Labels: in progress
