### ISSUE TITLE
VCF file created through vgs is erroneous. It has more number of bases than original fasta file and also its coordinates do not match with the original fasta file.

### ISSUE THREAD

**Issue by ziaursani** [vgteam/vg#2129] opened 2019-02-24 01:26 UTC
Please describe:

1. What you were trying to do
2. What you wanted to happen
3. What actually happened
4. What data and command line to use to make the problem recur, if applicable

```
Format code blocks or terminal copy-pastes like this, between triple backticks.
```

**Comment by adamnovak** [comment] 2019-02-25 18:48
Hello @ziaursani. Thanks for reporting this issue.

Unfortunately, I haven't ever seen the problem you are describing here. When I do variant calling with vg, and when we do it in our tests, we get VCFs where the coordinates do seem to match up with the input FASTA file. For example:

```
# Build a test graph
vg construct -r test/small/x.fa -v test/small/x.vcf.gz > x.vg
vg index -x x.xg x.vg
# Simulate some error-free reads form it 
vg sim -a -x x.xg -n 1000 > reads.gam
# Augment/pileup
vg augment x.vg reads.gam -a pileup -Z x.trans -S x.support > x.aug.vg
# Call variants based on the simulated error-free reads
vg call x.aug.vg -s x.support > called.vcf
# Pull out the position and ref sequence for each variant
zcat test/small/x.vcf.gz | grep -v "#" | cut -f2,4 | sort > possible-positions.txt
cat x.called.vcf | grep -v "#" | cut -f2,4 | sort > observed-positions.txt
# Find the ones unique to the called version
comm -1 -3 possible-positions.txt observed-positions.txt 
```

I get a few lines of output from this, each of which is a variant with a unique position/ref sequence combination that didn't appear in the input VCF used to build the graph. But I checked them out, and they seem to be re-spellings of the input (e.g. left-shifting existing variants), or mergings of adjacent variants. They definitely all still agree with the input FASTA. And the vast majority of the variants are spelled exactly as given in the input VCF.

You can check that a VCF agrees with a FASTA by trying to build a graph with it: `vg construct -r whatever.fa -v whatever.vcf`. If the ref sequences of any variants don't match the sequence in the FASTA, vg will complain. If it doesn't complain, they match up.

Could you possibly attach to this issue the input files you are using to get vg to produce a VCF where the coordinates don't match up? Or can you show some examples of VCF records called by vg that don't agree with your FASTA, and explain how exactly they disagree?

**Comment by ziaursani** [comment] 2019-02-26 00:57
I do the following
# Construct
vg construct -r reference.fa > graph.vg 

# Index
vg index -x graph.xg -g graph.gcsa graph.vg 

# Map
vg map -f reads.fq -g graph.gcsa -x graph.xg > mapped.gam

# Pileup/Augment
vg augment -a pileup -Z samp.trans -S samp.support graph.vg mapped.gam > samp.aug.vg 

# Call
vg call -z samp.trans -s samp.support samp.aug.vg > calls.vcf 

The resulting vcf shows length of sequence more than actual length of fasta file. Its coordinates do not match with the fasta file. When I construct graph, vg complains. I even see strange values in the reference field of vcf. I am attching that vcf file.

[NCYC78.docx](https://github.com/vgteam/vg/files/2903261/NCYC78.docx)

**Comment by adamnovak** [comment] 2019-02-26 18:08
OK, I can see part of your problem. The contig line in the VCF header looks like this:

```
##contig=<ID=chrXII:450575..469931,length=19362>
```

It looks like you have a FASTA for just a small region of a chromosome, and you built a graph for that and are now calling against it. That should work. But something has gone wrong, because the bounds 469931-450575 indicate that you should have a sequence of length 19356, but you actually seem to have 6 extra bases, for a length of 19362.

Can you attach the FASTA file you used to construct the graph? And the original VCF used to build the graph? Please just pack it up in a .zip or a .gz instead of pasting it into Word. I want to see if the FASTA sequence has these extra 6 bases to begin with (i.e. its name is just wrong), or if running it through vg construct is producing an incorrect path in the graph that gains 6 extra bases somehow.

I think the "strange values in the reference field" in the VCF is just the contig name. The FASTA must literally have a sequence name with numbers in it:

```
>chrXII:450575..469931
```

vg doesn't try to interpret those numbers; it sees a sequence named with that name, and numbers the bases within it 1, 2, 3..., n. So the variants in the output VCF have positions that are their position relative to the start of the input sequence.

If you want your VCF to be in terms of the full `chrXII` coordinate space, you can use some of these options to `vg call`:

```
    -r, --ref ARG                    use the path with the given name as a reference path (can repeat) [{}]
    -c, --contig ARG                 use the given name as the VCF name for the corresponding reference path (can repeat) [{}]
    -l, --length ARG                 override total sequence length in VCF for the corresponding reference path (can repeat) [{}]
    -o, --offset ARG                 offset variant positions by this amount in VCF [0]
```

You would do something like:

```
vg call -z samp.trans -s samp.support samp.aug.vg -r "chrXII:450575..469931" -c "chrXII" -o 450574 -l $LENGTH_OF_FULL_CHRXII > calls.vcf
```

Every variant that would be called on "chrXII:450575..469931" will instead be emitted on "chrXII", and have its position bumped up by 450,574 bases (so what would be position 1 is now position 450,575). The length value given to `-l` is what will appear in the VCF contig header.

Does that help?

**Comment by ziaursani** [comment] 2019-02-28 10:48
I have now attached the fasta file. When I talked about strange values in vcf, I meant to say values like AN, CN, GN, TN & N in the reference field instead of A, C, G & T. The coordinates of vcf file do not match with the fasta file. VG complains about this problem when we try to construct a graph.

[S288c_rDNA_cracker.zip](https://github.com/vgteam/vg/files/2914599/S288c_rDNA_cracker.zip)

**Comment by glennhickey** [comment] 2019-03-01 15:34
I think the issue is the Windows-style carriage returns in the fasta file.  Each line of `S288c_rDNA_cracker.fasta` ends with `\r\n`, whereas vg is expecting `\n`.  These `\r`'s are then interpreted as unknown bases once they wind up in the graph, and `vg call` outputs them as `N`'s.

You can see this with `vg view -j graph.vg  | jq . | head -10` which gives
```
{
  "node": [
    {
      "sequence": "CCAATGAATTTATATCAAGCAGTGTCTATTGC",
      "id": "1"
    },
    {
      "sequence": "TGCTTCTGAGAAATCACTGGGTCGTGGC\rACG",
      "id": "2"
    },
```
(see the \r at the end of the second sequence).  This is indeed a bug in `vg construct` which needs to do a better job of detecting hidden characters.  

You can also fix your input by stripping out the `\r`'s, ex:
```
sed 's/\r$//' S288c_rDNA_cracker.fasta > S288c_rDNA_cracker.fixed.fasta
```

**Comment by adamnovak** [comment] 2019-03-01 17:57
We probably need to go thinker around in fastahack to fix this
properly. We'll have to revise some of its newline counting logic to
account for length-2 line separators:

https://github.com/vgteam/fastahack/blob/b5d42afcb1356e0ee15ef601614184928f5ed65e/Fasta.cpp#L300-L303

We also probably will have to dispense with the use of `getline`.

If some but not all lines end in \r\n, I don't know if fastahack will
ever be able to deal with the file properly, because it requires all
lines to be the same length. But if it is consistently \r\n we should
be able to deal with it.

**Comment by adamnovak** [comment] 2019-03-01 18:00
This is a duplicate of https://github.com/ekg/fastahack/issues/5 now that we've figured out the underlying problem.

**Comment by adamnovak** [comment] 2019-03-04 18:30
OK, this should be fixed in vg master. I've modified fastahack to strip out \r characters from the sequence, and to account for their space when reading data from the FASTA.

**Comment by ziaursani** [comment] 2019-03-04 18:35
I removed \r through notepad++. Now the vcf file shows the length of 19356, one less than the actual length. Furthermore, its coordinates are also out by one base.

**Comment by adamnovak** [comment] 2019-03-04 18:53
Hm. This is different from VCF coordinates being natively 1-based, right?

Can you provide your modified FASTA file? When I strip out the '\r' characters with `tr`, and do this:

```
cat S288c_rDNA_cracker.fasta | tr -d '\r' > fixed.fa
vg construct -r fixed.fa > x.vg
vg index -x x.xg x.vg
vg sim -a -x x.xg -n 1000 > reads.gam
vg augment x.vg reads.gam -a pileup -Z x.trans -S x.support > x.aug.vg
vg call x.aug.vg -s x.support -z x.trans > called.vcf
```

I get a length of 19357 in the VCF header.

**Comment by ziaursani** [comment] 2019-03-05 13:36
Sorry I was doing some procedural mistake. Now it is fine. Thanks for your help.

**Closed** 2019-03-05 18:38 UTC
