### ISSUE TITLE
GCSA constructor failed

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#1758] opened 2018-06-25 13:29 UTC
Please describe:

1. What you were trying to do
Build an e-coli pan genome.
2. What you wanted to happen
Get a VG file for an e-coli pan genome
3. What actually happened
Got a stacktrace ;)
4. What data and command line to use to make the problem recur, if applicable
An ecoli.fa of 631mb, 187mb gzipped

End of the log file.
```
GCSA::GCSA(): Step 3 (path length 64 -> 128)
PathGraph::prune(): 78172156 -> 75296741 paths (53142420 ranges)
PathGraph::prune(): 43321762 unique, 0 redundant, 24890515 unsorted, 7084464 nondeterministic paths
PathGraph::prune(): 2.69035 GB in 1 file(s)
PathGraph::read(): File 0: Read 75296741 order-64 paths
terminate called after throwing an instance of 'std::runtime_error'
  what():  sd_vector: source list is not sorted.
ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug.
```

Stack trace of error
```
Stack trace (most recent call last):
#16   Object "/scratch/uuw_sparql/jerventest/vg", at 0x4cc079, in _start
#15   Object "/scratch/uuw_sparql/jerventest/vg", at 0x16ab208, in __libc_start_main
#14   Object "/scratch/uuw_sparql/jerventest/vg", at 0x406510, in main
#13   Object "/scratch/uuw_sparql/jerventest/vg", at 0x8371c7, in vg::subcommand::Subcommand::operator()(int, char**) const
#12   Object "/scratch/uuw_sparql/jerventest/vg", at 0x820660, in main_msga(int, char**)
#11   Object "/scratch/uuw_sparql/jerventest/vg", at 0x81dd56, in main_msga(int, char**)::{lambda(vg::VG*)#4}::operator()(vg::VG*) const
#10   Object "/scratch/uuw_sparql/jerventest/vg", at 0xb55ba5, in vg::build_gcsa_lcp(vg::VG&, gcsa::GCSA*&, gcsa::LCPArray*&, int, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
#9    Object "/scratch/uuw_sparql/jerventest/vg", at 0xe20c90, in gcsa::GCSA::GCSA(gcsa::InputGraph&, gcsa::ConstructionParameters const&)
#8    Object "/scratch/uuw_sparql/jerventest/vg", at 0xe52e1b, in gcsa::PathGraph::extend(unsigned long)
#7    Object "/scratch/uuw_sparql/jerventest/vg", at 0xe522d6, in gcsa::ValueIndex<gcsa::PathNode, gcsa::FromGetter>::ValueIndex(std::vector<gcsa::PathNode, std::allocator<gcsa::PathNode> > const&) [clone .constprop.824]
#6    Object "/scratch/uuw_sparql/jerventest/vg", at 0xe2b1e1, in sdsl::sd_vector<sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >::sd_vector<__gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > > >(__gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >)
#5    Object "/scratch/uuw_sparql/jerventest/vg", at 0x15e9713, in __cxa_throw
#4    Object "/scratch/uuw_sparql/jerventest/vg", at 0x15e91e0, in std::terminate()
#3    Object "/scratch/uuw_sparql/jerventest/vg", at 0x15e9195, in __cxxabiv1::__terminate(void (*)())
#2    Object "/scratch/uuw_sparql/jerventest/vg", at 0x15e9374, in __gnu_cxx::__verbose_terminate_handler()
#1    Object "/scratch/uuw_sparql/jerventest/vg", at 0x16bba50, in abort
#0    Object "/scratch/uuw_sparql/jerventest/vg", at 0xdf9c07, in raise

```

**Comment by adamnovak** [comment] 2018-06-25 17:53
@jltsiren This seems like something you might know how to fix.

**Comment by jltsiren** [comment] 2018-06-25 18:18
It's hard to say anything without the data and the specific commands used. Which compiler are you using?

The crash is basically the following:
1. Sort a vector of structs `paths` by integer keys `from` using `__gnu_parallel::sort()` or `std::sort()`, depending on the compiler.
2. Create a vector of distinct keys. (Take `paths[i].from` if `paths[i].from != paths[i-1].from`.)
3. Throw an exception, because `std::is_sorted()` says that the vector of keys is not sorted.

**Comment by JervenBolleman** [comment] 2018-06-25 19:40
@jltsiren this is the static build of 1.8.0. @adamnovak which  compiler do you use?

**Comment by jltsiren** [comment] 2018-06-25 20:01
Please share the data. It's easier to debug when the input is exactly the same.

**Comment by adamnovak** [comment] 2018-06-25 20:28
I believe that that build was with g++ (GCC) 8.1.0.

**Comment by JervenBolleman** [comment] 2018-06-26 08:43
For the record, I shared the input data with @jltsiren outside of github.

**Comment by jltsiren** [comment] 2018-06-28 22:05
I had `vg msga` running with this data using both the static v1.8.0 binary and a locally compiled VG that was a bit more recent. Unfortunately AWS killed the instance just before I was going to check the final logs.

Both runs had proceeded past the point where @JervenBolleman reported the crash. Neither run produced exactly the same numbers (e.g. `PathGraph::prune(): 78172156 -> 75296741 paths (53142420 ranges)`), and the two VG versions also produced slightly different numbers. The latter was probably caused by changes to the alignment code after v1.8.0.

Possible reasons for the differences between my v1.8.0 run and the run @JervenBolleman reported:
* `vg msga` is not deterministic.
* The static v1.8.0 binary is not truly static but depends on local libraries.
* The behavior of `vg msga` depends on locale on other environmental factors.

Any of these could have caused the crash, though the precise point of crash still looks weird. Harware issues could also have been the reason.

**Comment by JervenBolleman** [comment] 2018-07-02 06:08
Just want to note that I restarted the process and it is processing further than the last time.
Same user account/env. No ECC warnings during either run. 
Treading issue is quite possible.
I will let you know if it succeeds.

**Comment by JervenBolleman** [comment] 2018-07-06 07:33
I could not reproduce the failure. It ran and I have a 126 ecoli pangenome graph in vg format.

**Comment by ekg** [comment] 2018-07-06 07:37
Cool! Would you be able to share it publicly? This is via msga?

**Comment by JervenBolleman** [comment] 2018-07-06 10:17
@ekg yes this is via msga, as these are Ensembl genomes ones I can share it publicly

**Comment by adamnovak** [comment] 2018-07-10 20:01
Since we can't seem to reproduce this, and don't have much an idea of what's really wrong here, I'm going to close this issue.

**Closed by adamnovak** 2018-07-10 20:01 UTC
Labels: bug
