### ISSUE TITLE
Mapping quality is max for reads mapping to multiple positions

### ISSUE THREAD

**Issue by ivargr** [vgteam/vg#1471] opened 2018-02-24 21:50 UTC
I am experiencing bad performance when using vg to map reads to repetitive regions of the genome, compared to linear aligners like bwa aln. For instance, when mapping a read that aligns perfectly to multiple positions in the genome, bwa will report a low maping quality whereas vg reports mapping quality 60. Is this expected behaviour? 

I have experienced this on a whole genome graph, but it is hard to share the data and the details. However, this small test reproduces the problem:

graph.json
```
"node": [{"sequence": "AACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGG", "id": 1}]}
```

reads.fq (contains a single reads that will map perfectly to many places in the genome):
```
@read1
AACCTTGGAAAACCCCTTTTGGGG
+
HHHHHHHHHHHHHHHHHHHHHHHH
```

Script used to map with vg:
```
vg view -Jv graph.json > graph.vg
vg index -k 11 -g graph.gcsa -x graph.xg graph.vg
vg map -d graph -f reads.fq -j
```

Output from vg (with mapping_quality **60**):
```
{"sequence": "AACCTTGGAAAACCCCTTTTGGGG", "path": {"mapping": [{"position": {"node_id": 1}, "edit": [{"from_length": 24, "to_length": 24}], "rank": 1}]}, "quality": "JycnJycnJycnJycnJycnJycnJycnJycn", "name": "read1", "mapping_quality": 60, "score": 34, "identity": 1.0}

```

**Doing this the "linear" way:**

reference.fasta:
```
>chr1
AACCTTGGAAAACCCCTTTTGGGG
AACCTTGGAAAACCCCTTTTGGGG
AACCTTGGAAAACCCCTTTTGGGG
AACCTTGGAAAACCCCTTTTGGGG
```

Mapping with bwa aln:
```
bwa index reference.fasta
bwa aln reference.fasta reads.fq > reads.sai
bwa samse reference.fasta reads.sai reads.fq
```

Output from bwa aln (5th column is **mapping quality 0**):
```
read1	0	chr1	49	0	24M	*	0	0	AACCTTGGAAAACCCCTTTTGGGG	HHHHHHHHHHHHHHHHHHHHHHHH	XT:A:R	NM:i:0	X0:i:4	X1:i:0	XM:i:0	XO:i:0	XG:i:0	MD:Z:24	XA:Z:chr1,+1,24M,0;chr1,+25,24M,0;chr1,+73,24M,0;
```

Note that bwa aln finds 4 optimal alignments (*X0:i:4*), which I guess is the reason it gives mapping quality 0. From previous commit messages and issues I find in this repo, it seems that vg is supposed to take into account the number of optimal alignments when computing mapping quality. Is that correct?

I am using version 1.6.0-506-gbf9b6f0.

**Comment by ivargr** [comment] 2018-02-25 13:46
Update: I did som digging, and found out that by using `vg mpmap` instead of `vg map` and `--mq-method 2` (exact mapping quality estimation), vg correctly assigns this mapping a low mapping quality score.

I wasn't aware of `mpmap` and have always used `vg map`. Is mpmap the preferred subcommand to use for mapping? Am I also correct in assuming that mq-method must be set to 2 for vg to include the other optimal alignments when computing the mapping quality?

**Comment by ekg** [comment] 2018-02-25 23:03
This is a bug related to the candidate alignments that are attempted. The aligner isn't considering multiple mappings in this case because of a mistake in the a cluster deduplication step that assumes you won't get repeats in the same node. Thank you for making such a clean test case. I think it will probably end up in our automated tests.

To demonstrate, this resolves the problem by chopping the single-node graph into smaller (5bp) nodes:

```
echo '{"node": [{"sequence": "AACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGGAACCTTGGAAAACCCCTTTTGGGG", "id": 1}]}' | vg view -Jv - | vg mod -X 5 - >g5.vg
vg index -k 11 -g g5.gcsa -x g5.xg g5.vg
vg map -d g5 -f r.fq -j -D
```

The output now shows the expected result:

```
Loading xg index g5.xg...
Loading GCSA2 index g5.gcsa...
Loading LCP index g5.gcsa...
[vg map] : min_mem_length = 7, mem_reseed_length = 11, min_cluster_length = 0
align_multi_internal(1, AACCTTGGAAAACCCCTTTTGGGG, 0, 0, 256, 1, 512, 0)
mems for read [["AACCTTGGAAAACCCCTTTTGGGG",["2:0","6:4","11:3","16:2"]]]
maybe_mq read1 inf 512 24 0 512 1 0 144.185 512
### clusters:
clusters:
1 MEMs covering 24 @ |2+:0,1,AACCTTGGAAAACCCCTTTTGGGG
1 MEMs covering 24 @ |6+:4,1,AACCTTGGAAAACCCCTTTTGGGG
1 MEMs covering 24 @ |11+:3,1,AACCTTGGAAAACCCCTTTTGGGG
1 MEMs covering 24 @ |16+:2,1,AACCTTGGAAAACCCCTTTTGGGG
{"quality": "JycnJycnJycnJycnJycnJycnJycnJycn", "sequence": "AACCTTGGAAAACCCCTTTTGGGG", "name": "read1", "path": {"mapping": [{"position": {"node_id": 2}, "edit": [{"from_length": 5, "to_length": 5}], "rank": 1}, {"position": {"node_id": 3}, "edit": [{"from_length": 5, "to_length": 5}], "rank": 2}, {"position": {"node_id": 4}, "edit": [{"from_length": 5, "to_length": 5}], "rank": 3}, {"position": {"node_id": 5}, "edit": [{"from_length": 5, "to_length": 5}], "rank": 4}, {"position": {"node_id": 6}, "edit": [{"from_length": 4, "to_length": 4}], "rank": 5}]}, "score": 34, "identity": 1.0, "secondary_score": [34, 34, 34]}
```

Before the aligner wasn't even considering the secondary alignments due to the deduplication. Now, it is and we get the expected mapping quality (0, or "null").

I am curious if you also see the same issue when mapping against a large graph. It would seem strange if you had repeats within a single node causing this problem there.

> I wasn't aware of mpmap and have always used vg map. Is mpmap the preferred subcommand to use for mapping?

`vg map` is and will be the prefered API for standard read mapping in vg. It has been validated in our manuscript and is capable of aligning efficiently against any kind of graph. `mpmap` is a multipath mapper that is designed to emit multipath mappings that each may describe many different paths through the graph. It can emit the best path as a single mapping. At present it is also limited to approximately DAG-like graphs. It has not undergone the level of validation that `map` has. If we find the methods in `mpmap` to be preferable to those in `map`, then we will expose the single path mode of `mpmap` via `map`, so this will remain the preferred API for generating graph alignments.

> Am I also correct in assuming that mq-method must be set to 2 for vg to include the other optimal alignments when computing the mapping quality?

Actually, this is not the case. The best two alignments (both of which may be optimal) are always used to compute the quality. If the mapper cannot find a second-best alignment then it reports the maximum mapping quality. In this case you have found a bug with the alignment deduplication that is not shared between `map ` and `mpmap`, and which gives rise to this issue. A fix will be in master shortly.

**Comment by ekg** [comment] 2018-02-25 23:34
I should eat a few of my words! The test you sent is harder to solve than I expected, and not just for vg map...

First, it is true that the cluster filtering code was removing the alternate alignments in this case. However, even resolving this doesn't completely resolve the issue as the alignments that were returned were exactly the same and so _they_ were filtered out. This is because the alignment between the read and the graph is always picking up the same node and the same sequence to run the alignment. As a result, it picks (by "chance") the first possible alignment.

Before, I had explored patching up the alignment by first walking the exact matches and then aligning the bits between them. This is the approach that @jeizenga has taken to its logical completion as the basis for multipath mapping. So, I assumed that the solution is to use an alignment technique like that in mpmap. Unfortunately, I tested it but it takes many minutes and doesn't return a result:

```
vg mpmap -x g.xg -g g.gcsa -f r.fq -S | vg view -a -
```

It also fails when I try on the chopped graph I described above:

```
vg mpmap -x g5.xg -g g5.gcsa -f r.fq -S | vg view -a -
```

So it seems that this particular test case is breaking both of vg's alignment tools in different ways!

Do you have an example that's not bound up with the issue of having the MEMs for the read all hitting the same node?

**Comment by ekg** [comment] 2018-02-26 00:09
For my future reference, this resolves the problem in this particular test case although not in a generic way...

```patch
@@ -3282,6 +3278,9 @@ double Mapper::compute_uniqueness(const Alignment& aln, const vector<MaximalExac
 }

 Alignment Mapper::align_cluster(const Alignment& aln, const vector<MaximalExactMatch>& mems, bool traceback) {
+    if (cluster_coverage(mems) == aln.sequence().size() && mems.size() == 1) {
+        return patch_alignment(mems_to_alignment(aln, mems), aln.sequence().size());
+    }
```

**Comment by ekg** [comment] 2018-02-26 17:50
I've done some experiments and I think I understand what you're seeing on the whole genome. The cause is different than the test case you submitted.

The `--hit-max` or `-c` parameter to `vg map` was set too low. As a result there were cases where there would be thousands of exact matches of the whole read but only unusual variants of the repeat that matched the read by chance (but not the "main" MEMs) would be considered.

The change makes an obvious difference in the ROC curves I get using `scripts/map-sim` on a whole genome human sample, so I think it's the right way to go. Thank you for bringing this to my attention.

**Comment by ivargr** [comment] 2018-02-26 18:15
Thanks for quick reply!

The test case I provided in my intial post seems to pass fine when splitting the graph into multiple nodes, so I don't see this as any serious problem/bug. Also, as you point out, this test case is probably not related to the problems I was experiencing on whole genome graph (where all my nodes anyway are capped to 32 bps).

I have been trying to dig more into the problems I was experiencing with high vg mapq to reads that bwa finds multiple optimal alignments for, and I do have several examples where vg is off (bwa aln finds multiple optimal alignments and gives mapq 0 while vg gives 60). I have, hower, not been able to reproduce this in smaller shareable tests yet. Do you think this problem might be solved by your recent commit? 

I'll try to check this again using your newest commit, and if I still observe weird things, I'll try to reproduce this on smaller tests or find some way to share it.

**Comment by ekg** [comment] 2018-02-26 19:25
@ivargr you should be good to test via the mappering branch at ef8d23f. Let me know if it fixes the problem. I was also to find a few cases like this. In the end they were some of the few remaining errors that vg was committing relative to bwa mem (single ended at least).

There is at least one more bug, where the paired end mapping in vg is not quite as sensitive as bwa mem. Let me know if you notice anything, you've already nudged me in the right direction :grin:

**Comment by ekg** [comment] 2018-03-01 10:55
@ivargr did you see the problem resolved when using the mappering branch?

**Comment by ivargr** [comment] 2018-03-01 11:37
Yes, I am happy to say that things got a lot better! I think what really made the change was manually setting *-k/--min-mem* low. For 50 basepair reads, when setting min-mem to 12, all reads that earlier got a wrong too high mapq (because vg did not find all optimal mappings) seemed to get a correct low mapq. I also needed to set hit-max to some limit (used 10k) in order for the mapping not to halt at some point. A low min-mem resulted in slower mapping, but much better results. After this change, I am not able to find any reads that vg has given too high mapq score to. :)

**Comment by ekg** [comment] 2018-03-01 16:25
These are changes that I've explored on the mappering branch. It specifically un-caps the hit limit. But what you say about setting a different `--min-mem` length for 50bp reads is interesting. Perhaps we should dynamically determine this somehow based on the read length. Right now it is only dynamically set based on the graph sequence size, and you can see the setting that's given in the debugging output `vg map -D` in the first few lines.

**Closed** 2018-03-02 13:56 UTC
