### ISSUE TITLE
vg circularize doesn't connect head node and tail node when path is specified in v1.22.0

### ISSUE THREAD

**Issue by hanzou666** [vgteam/vg#2666] opened 2020-03-08 02:45 UTC
**1. What were you trying to do?**

I was trying to circularize a flat graph.

**2. What did you want to happen?**

When I use `vg circularize` with specifying a path, I expected that the command would not only round the path, but also add a link record connecting the head node and the tail node in the graph.
​
In <= v1.21.0, the command worked as expected, although I didn't check all version.

**3. What actually happened?**

As shown in 5, a flag `is_circular` was set, but there was no link record.

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Place stacktrace here.
```

**5. What data and command can the vg dev team use to make the problem happen?**

In v1.21.0 (and probably other earlier version):
​
```shell
$ vg version
vg version v1.21.0 "Fanano"
Compiled with g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 on Linux
Linked against libstd++ 20181206
Built by anovak@hex
$ echo -e ">x\nATGC" > x.fa
$ vg construct -r x.fa | vg circularize -p x - > x.vg
$ vg stats -A x.vg
cyclic
$ vg view x.vg
H	VN:Z:1.0
S	1	ATGC
P	x	1+	4M
L	1	+	1	+	0M
```
​​​
In v1.22.0:
​
```shell
$ vg version v1.22.0 "Rotella"
Compiled with g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 on Linux
Linked against libstd++ 20181206
Built by root@d0298e233669
$ vg construct -r x.fa | vg circularize -p x - > x.vg
$ vg stats -A x.vg
acyclic
$ vg view -j x.vg | jq '.path[].is_circular' 
true
$ vg view x.vg  # there is no links
H	VN:Z:1.0
S	1	ATGC
P	x	1+	4M
```

**6. What does running `vg version` say?**

```
v1.20.0, v1.21.0 and v1.22.0
```

**Comment by maxgmarin** [comment] 2020-03-08 14:59
I have also found that when using "vg msga" (vg 1.22.0 ) with the circularize option causes the program to crash. This was not an issue in previous versions.

**Comment by ekg** [comment] 2020-03-08 15:56
That's curious! Could this have to do with the adoption of the HandleGraph
model in msga?

**Comment by jeizenga** [comment] 2020-03-08 19:39
I refactored circularize to use the handle graph interface a little while ago. It passed the integration tests, but it's possible that the tests have a hole. I didn't make any changes to msga though.

**Comment by jeizenga** [comment] 2020-03-09 21:37
I just merged a PR that should fix the problem where circularize no longer created and edge. I'm leaving this issue open, though, because I'm not sure that the crash on MSGA is the same bug.

**Comment by adamnovak** [comment] 2020-03-16 19:39
Is this fixed now? Can I close it?

**Comment by jeizenga** [comment] 2020-03-16 20:01
I think it's still in the same state as when I made my last comment. Organizationally speaking, it might make sense to re-title this issue or else close it make a new issue for the MSGA bug.

**Comment by adamnovak** [comment] 2020-03-18 17:56
OK, I'm going to close this.

@maxgmarin Can you report a new issue for the MSGA circularize crash, with the details needed to reproduce it? Does it happen every time you use the flag, on arbitrarily small/simple inputs? Or only on certain inputs?

**Closed by adamnovak** 2020-03-18 17:56 UTC
