### ISSUE TITLE
Constructing the genome graph progressively with assemblies, and then SV

### ISSUE THREAD

**Issue by clairemerot** [vgteam/vg#3194] opened 2021-02-09 19:21 UTC
Hello,
I was wondering whether vg construct is able to iterate? or to build on a graph reference instead of a linear reference?

My goal (and I hope it makes sense) would be to use 
1) 1 reference + 1 assembly of another sample (contig-level)  to build a 1st pangenome graph. This can be done in minigraph or PGGB?

2) Expand this pangenome graph (need to convert gfa to vg) by using a vcf of SV (inferred from short reads or long-reads on much more samples - whole genome but not assembled). This to be done in vg? 

3) Possibly add more variants ? (or is it better to merge variants in a single vcf before step 2)?

Thanks a lot for your hard work on this tool, this is super useful!!
Claire

**Comment by joehagmann** [comment] 2021-02-10 09:38
+1
I'd welcome as well guidance to augment a variant graph with one or several vcf's. I only see the possibility to augment with mapping files. I like to avoid augmenting a graph with >100 short read libraries, since I can do that only serially, right?

One workaround I see atm is to build 'pseudo-genomes' that have the vcf variants built into them, and feed them as further assemblies into the graph generation step (pggb/minigraph).

Any help is much appreciated.

@clairemerot `vg convert` converts pggb's gfa output to vg, and the next vg release will likely make that possible for minigraph's rGFA output as well, see #3160

**Comment by ekg** [comment] 2021-02-10 10:01
In effect, augmentation is just mapping new sequences onto other sequences that you've put into the graph.

In practice, this means that it's simplest to just put all the sequences together in the graph up front.

I'd suggest collecting the various parts as sequences. So you'd have:

1. your reference
2. the second assembly
3. SV alleles obtained from other assemblies / mapping / contigs that you have in hand

All three of these sources imply some sequences that you can represent in FASTA. The assemblies are in FASTA, and if your SV detection is based on alignment of assembled contigs to the reference, this means that you have some more FASTA sequences that you can put into the pot.

But, if (3) is based on alignment of long reads and variant calling (into VCF), then you would want to convert your SV calls into sequences that you can map onto your references. I'd suggest scripting a process that adds the reference flanks of some (large) length to the sequences of the SV alleles, making a kind of contig for each SV allele. Note that in the case of a deletion, you might only have the flanking sequences from the reference.

Then, you can put all of these sources together in a single FASTA, ensure that the sequence names are unique, and then provide this as input to pggb. Assuming that you have clear chromosome segregation, I would also suggest partitioning things by chromosome and running pggb on each piece separately, as this will reduce the likelihood and damage of any mismappings. The process that we're using for the HPRC is described here: https://github.com/pangenome/HPRCy1

Finally, you can use tools in vg to combine the graphs together. You'd want to use similar steps as shown in the vg documentation on the wiki https://github.com/vgteam/vg/wiki/Working-with-a-whole-genome-variation-graph#node-id-coordination. Then, things should work as expected for using the graph for mapping short read data with vg map and vg giraffe. Combining things together in this way will make it trivial to project your alignments into your two reference assembly spaces, and you will be able navigate the graphs using the coordinate spaces of both of the reference assemblies you've included. By putting everything into the pggb process together, you'll also mitigate issues caused by differential SV representation.

**Comment by joehagmann** [comment] 2021-02-10 10:40
Thanks a lot for this comprehensive answer, @ekg. This is quite a bit of an effort, but I see the benefits, esp. in normalizing SVs.

Out of curiosity and maybe to compare: Just now I found `vg add` which is exactly for integrating vcf's into a graph. It seems to not be followed on nor to be found in common vg documentation. Is it recommended to use?

Sorry for taking over this issue @clairemerot. But I hope it helps, and I think after that question I'm covered ;-)

**Comment by glennhickey** [comment] 2021-02-10 13:45
I'd put `vg add` in the "use at your own risk" category.  Yes, it can add VCF variants to a graph, but it hasn't been maintained for some time, nor seen much general use.  It should work on simple examples though. 

To the original point, I'll echo what Erik said in that it's best to either get everything into VCF and make a graph from that with `vg construct`, or to convert everything to contigs and make a graph from aligning them with something like `pggb`.

**Comment by clairemerot** [comment] 2021-02-10 13:55
Thanks Eric Garrison for this detailed answer!
And thank you Glenn Hickey for the precision.
@joehagmann, no problem for jumping in, that's the whole point of posting on GitHub! I'd be interested to hear how you will manage to sort that on your own data, we can get in touch.

Yes, I am in the second case for step 3 (SV detected by short-reads and Sv detected by long-reads). That makes sense to transform them into alternative local contigs. One fasta per chromosome is a good point. Would you recommend a minimum length around the SV to ensure good integration into the assembly-based graph? 1kb on each side of the SV? 5kb? 

I'll try and keep you posted, if that can help someone!
Thanks a lot
Claire

**Comment by ekg** [comment] 2021-02-10 14:00
I'd suggest a big flank on each side. You want to be sure that the piece, when mapped back to any of the references, won't mismap to another location. That's really all. You could also construct a shorter alignment with just a few bp of flank and write a PAF directly.

Please do share what works!

**Comment by clairemerot** [comment] 2021-02-10 14:24
Oh, making a PAF file from the vcf might save the first step of PGGB right? 
But then, is PGGB able to integrate one PAF/or fasta for the second assembly, and one PAF for the SV pseudo-contig? I'll look more into that, I'm not familiar enough with PBBG at the moment to figure out how to squiz this but I'll keep you in touch for sure!
Thanks a lot
Claire

**Comment by ekg** [comment] 2021-02-10 14:39
pggb takes a FASTA as input. But, it's just a shell script. It would be
easy to take an additional PAF file as input or add the functionality you
want. That could be a feature request or a hack you do.

**Comment by jeizenga** [comment] 2021-03-03 03:01
It seems like this question has been largely resolved, so I'm going to close the issue. Let me know if you still have further questions.

**Closed by jeizenga** 2021-03-03 03:01 UTC
