### ISSUE TITLE
vg bluntification bug

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#896] opened 2017-07-26 17:03 UTC
For the following graph, it aborts with the following error:

```
[VG::bluntify] warning! overlaps of {"overlap": 151, "from": 2534702, "to": 2478220, "from_start": true} are not identical and could not be resolved by alignment
o1:  ATTTTAAAATTTCCAGTTACGAAAATTCTTGTTTTTGACAAAAATTTAATGAATAAATAAAATTGTTTGTGTTTGTTACCTCTGGGCCCCGATTGCTCGAATGCCCAAAGAAAAAGTTGCAAAGATATGAAAACTCCACAGTGTGTTGTAT
o2:  ATACAACACACTGTGGAGTTTTCATATCTTTGCAACTTTTTCTTTGGGCATTCGAGCAATCGGGGCCCAGAGGTAACAAACACAAACAATTTTATTTATTCATTAAATTTTTGTCAAAAACAAGAATTTTCGTAACTGGAAATTTTAAAAT
aln: {"path": {"mapping": [{"position": {"offset": 141}, "edit": [{"from_length": 10, "to_length": 10}, {"to_length": 141, "sequence": "TTCCAGTTACGAAAATTCTTGTTTTTGACAAAAATTTAATGAATAAATAAAATTGTTTGTGTTTGTTACCTCTGGGCCCCGATTGCTCGAATGCCCAAAGAAAAAGTTGCAAAGATATGAAAACTCCACAGTGTGTTGTAT"}]}]}, "score": 10, "identity": 0.066225165562913912}
[VG::bluntify] warning! overlaps of {"overlap": 151, "from": 2534702, "to": 2506127, "from_start": true} are not identical and could not be resolved by alignment
o1:  ATTTTAAAATTTCCAGTTACGAAAATTCTTGTTTTTGACAAAAATTTAATGAATAAATAAAATTGTTTGTGTTTGTTACCTCTGGGCCCCGATTGCTCGAATGCCCAAAGAAAAAGTTGCAAAGATATGAAAACTCCACAGTGTGTTGTAT
o2:  ATACAACACACTGTGGAGTTTTCATATCTTTGCAACTTTTTCTTTGGGCATTCGAGCAATCGGGGCCCAGAGGTAACAAACACAAACAATTTTATTTATTCATTAAATTTTTGTCAAAAACAAGAATTTTCGTAACTGGAAATTTTAAAAT
aln: {"path": {"mapping": [{"position": {"offset": 141}, "edit": [{"from_length": 10, "to_length": 10}, {"to_length": 141, "sequence": "TTCCAGTTACGAAAATTCTTGTTTTTGACAAAAATTTAATGAATAAATAAAATTGTTTGTGTTTGTTACCTCTGGGCCCCGATTGCTCGAATGCCCAAAGAAAAAGTTGCAAAGATATGAAAACTCCACAGTGTGTTGTAT"}]}]}, "score": 10, "identity": 0.066225165562913912}
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 152) > this->size() (which is 151)
```

https://transfer.sh/12DVKW/yeast.illumina.SK1_Y12.cov30.chrall.int.gfa

Could you please fix it quickly?

**Comment by adamnovak** [comment] 2017-07-26 18:02
OK so there's two things going on here.

The first is that trying to convert this GFA to VG format spams thousands of warnings about the overlaps not being resolvable. Here's a subset of your graph that produces that problem:

```
S       2534702 ATACAACACACTGTGGAGTTTTCATATCTTTGCAACTTTTTCTTTGGGCATTCGAGCAATCGGGGCCCAGAGGTAACAAACACAAACAATTTTATTTATTCATTAAATTTTTGTCAAAAACAAGAATTTTCGTAACTGGAAATTTTAAAAT
S       2478220 ATACAACACACTGTGGAGTTTTCATATCTTTGCAACTTTTTCTTTGGGCATTCGAGCAATCGGGGCCCAGAGGTAACAAACACAAACAATTTTATTTATTCATTAAATTTTTGTCAAAAACAAGAATTTTCGTAACTGGAAATTTTAAAAT
L       2534702 -       2478220 +       151M
```

Here we have two nodes with identical, non-palindromic sequences, and an edge alleging an overlap between the *reverse complement* of the first one and the forward version of the second. That leads to vg trying to resolve an overlap between two strigns that don't really overlap and complaining.

I suspect that whatever tool generated this file isn't interpreting the GFA spec correctly; [the spec says](https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md#l-link-line) that a `-` in a Link line means to take the reverse complement of the referenced node sequence, not to attach to its end (which is what I assume the generating program is trying to say here).

I suspect that if you fix the input to be sensical, vg will be able to handle it correctly.

That said, no amount of nonsensical GFA ought to be able to actually crash VG, which is the second issue here. I will continue investigating the out of bounds access. However, you shouldn't wait around for that, because even once it's fixed, the file you provided probably won't make a useful VG graph.

**Comment by adamnovak** [comment] 2017-07-26 21:26
I'm having trouble reproducing the out of bounds access; reading the GAM file, with stderr dumped to /dev/null so it doesn't spend hours printing, finished just fine under gdb.

**Comment by edawson** [comment] 2017-08-04 15:27
The out of bounds looks to be post-parsing, but I also can't replicate it.

@shilpagarg make sure you've done a recent `git submodule update --recursive --init && make` so that you catch the latest GFA parser.

Aside: This GFA has no version header line. That isn't what's causing the error, and header lines aren't required, but it is safer if they are there. Which tool produced this GFA?

**Comment by adamnovak** [comment] 2017-08-14 16:53
Since we weren't able to reproduce the issue, I'm going to close this ticket. If it reoccurs, please let us know.

**Closed by adamnovak** 2017-08-14 16:53 UTC
