### ISSUE TITLE
Some warnings appeared in vg call using  graph which was produced by following "The Cactus Pangenome Pipeline".

### ISSUE THREAD

**Issue by lucky-syn** [vgteam/vg#3502] opened 2021-12-18 03:54 UTC
**1. What were you trying to do?**
Mapping short-reads to  graph-based genome and calling variants. 
(The graph-based genome was produced based on graph which constructed by assembled genomes. 
Followed: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md)

**2. What did you want to happen?**
producing VCF profile without warning.

**3. What actually happened?**
VCF file produced with warnings:
 Warning [vg call]: Unable, due to bug or corrupt path information, to trace reference path through snarl {"directed_acyclic_net_graph": true, "end": {"backward": true, "node_id": "29467443"}, "parent": {"end": {"node_id": "2446394"}, "start": {"backward": true, "node_id": "2403876"}}, "start": {"node_id": "29467441"}, "start_end_reachable": true}
Warning [vg call]: Unable, due to bug or corrupt path information, to trace reference path through snarl {"directed_acyclic_net_graph": true, "end": {"backward": true, "node_id": "38533131"}, "end_self_reachable": true, "parent": {"end": {"node_id": "2446394"}, "start": {"backward": true, "node_id": "2403876"}}, "start": {"node_id": "38522593"}, "start_end_reachable": true}

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
No stacktrace.
```

**5. What data and command can the vg dev team use to make the problem happen?**
vg mod -t 48 -X 256 pangenome.vg  > new.vg
vg view -g new.vg --threads 48 >new.gfa
vg autoindex --workflow giraffe -g new.gfa -p pangenome -t 19 -R XG
vg snarls -T pangenome.xg -t 19 >pangenome.snarls
vg giraffe -Z pangenome.giraffe.gbz -m pangenome.min -d pangenome.dist -t 19 -f C1_1.paired.fastq.gz -f C1_2.paired.fastq.gz --sample C1 --output-format gam --progress >C1.aln.gam
vg pack -x pangenome.xg -g C1.aln.gam  -o C1.aln.pack  -Q 20 -t 19
vg call pangenome.xg -k  C1.aln.pack -r pangenome.snarls -s C1 -t 19 > C1.aln.snarls.vcf

**6. What does running `vg version` say?**
```
vg version v1.36.0 "Cibottola"
Compiled with g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 on Linux
Linked against libstd++ 20200808
Built by stephen@lubuntu
```

I had add parameter -n (refer to #3286) , but there were the some errors (terminate called recursively; terminate called after throwing an instance of 'std::runtime_error'). Please advise on what I'm doing wrong here.

Thank you

**Comment by adamnovak** [comment] 2021-12-21 17:56
It looks like your graph has a couple sites that we're having trouble finding the reference path through. In a graph made from assemblies, it's going to be trying to call against all the assemblies as reference paths. I *think* that if some of them are shorter than others and stop in the middle of sites, you could get these warnings.

You can try explicitly setting the paths you want your VCF called against by passing `-p path_name` options for each of them to `vg call`. That could reduce the number of warnings you get.

If you want to see if the problem is that a path stops in the middle of a site, you can try and pull out the relevant part of the graph and look at it to see what the paths are up to there. For snarl:

```
{"directed_acyclic_net_graph": true, "end": {"backward": true, "node_id": "29467443"}, "parent": {"end": {"node_id": "2446394"}, "start": {"backward": true, "node_id": "2403876"}}, "start": {"node_id": "29467441"}, "start_end_reachable": true}
```

That one runs from node 29467441 forward to node 29467443 reverse. Those are only a couple IDs apart, and mostly node IDs are assigned in a topologically-sorted way, so I think you can just look at that range of node IDs. You can pull out a node ID range from the graph and a little context around it, and then render it and the paths through it with GraphViz:

```
vg find -x pangenome.xg --node-range 29467441:29467443 --context 2 > part.vg
vg view --dot --show-paths part.vg > part.dot
dot -Tsvg -o part.svg part.dot
```

Then open up `part.svg` in your favorite viewer, like a browser, and see if any of your reference paths stop in the middle of the bubble between nodes 29467441 and 29467443.

If your reference path goes straight through the site, then we do have a real bug in `vg call`. Then we'd need to get a copy of the `pangenome.xg` and the ` C1.aln.pack`, or at least that `part.vg`, to try and replicate and fix it.

**Comment by lucky-syn** [comment] 2021-12-29 01:50
Thanks for your replay. I added the parameter "-p path_name" and the warnings was absent.

**Comment by adamnovak** [comment] 2022-01-03 14:48
Great! I'm going to close this issue; if we can find somewhere to better document that you want to pass `-p` when calling against alignment-based pangenome graphs, we ought to.

**Closed by adamnovak** 2022-01-03 14:48 UTC
