### ISSUE TITLE
surjected reads change reference position in output

### ISSUE THREAD

**Issue by ChriKub** [vgteam/vg#1724] opened 2018-06-07 12:58 UTC
Please describe:

1. What you were trying to do

I want to surject error free, simulated reads in a gam file, mapped to a flat, variant free graph, into a sam file.

2. What you wanted to happen

I want the reads to have the same reference position in the sam file, that they had in the gam file, as it is a linear reference and the vg map mapping has an identity of 1, thus their position should not change.

3. What actually happened

~50% of the reads change their position in the reference. The new position is always the same reference position that can be determined using bwa mem. Example:

vgPos: 21368094
bwaPos: 21367847
vgSurjectPos: 21367847

4. What data and command line to use to make the problem recur, if applicable

I uploaded a data set to use [here](https://owncloud.tuebingen.mpg.de/index.php/s/D9ZHUdw5BI4FQ1C)
```
vg map -d TAIR10_Chr1 -t 40 -f TAIR10.fq.gz > vg.map.gam
vg surject -x TAIR10_Chr1.xg -p TAIR10_Chr1 -s vg.map.gam > vg.map.2.sam
bwa mem -t 40 TAIR10_Chr1.fasta TAIR10.fq.gz > bwa.mem.sam
```
I am running version v1.8.0-24-g739b29e

**Comment by jeizenga** [comment] 2018-06-08 15:22
@cmarkello Is this the same behavior you were seeing?

**Comment by ekg** [comment] 2018-06-08 15:36
There is a tolerance given to the map-sim script that must be taking care
of this or making it so we don't see the issue.

**Comment by adamnovak** [comment] 2019-02-26 20:26
I'm not able to reproduce this issue with current master vg:

```
$ vg version
vg version v1.14.0-23-g2f02b148 "Quadrelle"
Compiled with g++ (GCC) 8.1.0 on Linux
Built by anovak@courtyard
```

This is what I did after getting all the linked files:

```
vg map -d TAIR10_Chr1 -t 40 -f TAIR10.fq.gz > vg.map.gam
vg surject -x TAIR10_Chr1.xg -p TAIR10_Chr1 -s vg.map.gam > vg.map.2.sam
bwa index TAIR10_Chr1.fasta
bwa mem -t 40 TAIR10_Chr1.fasta TAIR10.fq.gz > bwa.mem.sam
# Get the positions assigned by surject
cat vg.map.2.sam | grep -v "^@" | cut -f1,4 | sort > surject.tsv
# Get the pre-surject positions and make them 1-based
vg view -aj vg.map.gam | jq -r  '[.name, (.refpos[0].offset | tonumber) + 1] | @tsv' | sort > orig.tsv
# Compare the positions for all the reads. Reports no differences.
diff orig.tsv surject.tsv
```

I *do* see differences between BWA's placements of reads and vg's placements of the same reads. But that's not necessarily a bug, I don't think, even though the graph is a linear graph.

I'm going to close this issue as having been already fixed last time we tinkered with surject. Please re-open it if it still seems like reads are getting moved.

I don't think this is really a dupe of #2131; the reads here aren't paired, and the orientations come through surject identically:

```
vg view -aj vg.map.gam | jq -r  '[.name, if .refpos[0].is_reverse then 16 else 0 end] | @tsv' | sort > orig.flags.tsv
cat vg.map.2.sam | grep -v "^@" | cut -f1,2 | sort > surject.flags.tsv
diff orig.flags.tsv surject.flags.tsv
```

**Closed** 2019-02-26 20:26 UTC
