### ISSUE TITLE
HGVM Graph Bakeoff vg graph for MHC

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#407] opened 2016-06-23 21:42 UTC
Hello,

Are the vg graphs from the HGVM Graph Bakeoff available for use? Or are they still in development? I'm having trouble building a graph for [MHC](https://github.com/vgteam/vg/issues/363) and would like to explore what else has been developed for this region, if possible.

**Comment by ekg** [comment] 2016-06-23 22:30
Are you using vg msga? If so what command line did you try? There is a post
on the wiki about this.
https://github.com/vgteam/vg/wiki/Long-read-assemblies-using-vg-msga

I would suggest a change from that document. I'm finding that setting
minimum alignment thresholds higher than the default helps. -P 0.9

Where did you get stuck?

**Comment by adamnovak** [comment] 2016-06-24 23:21
You can download the bakeoff graph submissions from the server at http://ga4gh-test1.cloudapp.net/

They're presented through a graph version of the GA4GH API; to get them you need to:

 * Install https://github.com/glennhickey/sg2vg
 * Find the URL of the graph you want in the TSV file linked from that web page (for example, `http://ga4gh-test1.cloudapp.net/cactus-brca2/`)
* Append the API version (`v0.6.g`) to the URL and download it with `sg2vg`. Since `sg2vg` spits out JSON, you'll want to use `vg view` to convert that into VG format.

A working command example:

```
sg2vg http://ga4gh-test1.cloudapp.net/cactus-brca2/v0.6.g | vg view -Jv - > test.vg
```

You might consider applying things like `vg mod -X 100` to chop the nodes to reasonable lengths, and `vg ids -s` to re-number the nodes according to a generalized topological sort (which makes the mapping heuristics work much better). These work in a pipeline like so:

```
sg2vg http://ga4gh-test1.cloudapp.net/cactus-brca2/v0.6.g | vg view -Jv - | vg mod -X 100 - | vg ids -s - > test.vg
```

**Comment by ekg** [comment] 2016-06-25 18:37
It would be beautiful to move past the mapping heuristics. It seems we are
close provided there is an embedded reference path.

**Comment by ekg** [comment] 2016-06-27 14:36
@hgibling I've been able to construct a graph using MSGA and the inputs you provided. I do get a heap of warnings, but when I validate the graph it seems to be OK. I'm extracting the input reference path which was associated with all the warnings now to check if it's valid.

**Comment by adamnovak** [comment] 2016-06-27 17:14
What we would really want to know is if path "6" from the input graph survives the MSGA process and is still spelling out the same sequence in the output graph.

**Comment by adamnovak** [comment] 2016-11-02 17:04
Since @ekg managed to make this graph, I'm going to close this issue. If you still have trouble getting the graph, please open another one.

**Comment by ekg** [comment] 2016-11-03 07:23
I haven't made it in some time...

I actually think here has been a regression here.

**Comment by adamnovak** [comment] 2017-01-12 18:26
We've been building Notch graphs with MSGA (and the non-threading mapper), so it ought to be possible to build this graph too. I'm going to close this issue again.

**Closed by adamnovak** 2017-01-12 18:26 UTC
