### ISSUE TITLE
clarification of xg warning during msga

### ISSUE THREAD

**Issue by hgibling** [vgteam/vg#363] opened 2016-05-25 18:40 UTC
Hello,

I'm using `vg` to build a graph of the MHC region on chromosome 6. I constructed a graph using the [GRCh38 reference sequence] (http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa) sequence and the [1000 genomes project VCF SNPs file](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions) for chromosome 6:
```
vg construct -R 6:28510120-33480577 -t 16 -m 32 -v SNPs-vcf -r reference-sequence > GRCh38-MHC-ref.vg
```

And then aligned the [alternate haplotypes](http://hgwdev.sdsc.edu/~anovak/hgvm/MHC/), following the parameters from the [wiki on msga](https://github.com/vgteam/vg/wiki/Long-read-assemblies-using-vg-msga#example), but with the `-z` flag for retaining parts of the original graph that aren't in the input paths:
```
vg msga -g GRCh38-MHC-ref.vg -f alt-MHC.fa -B 128 -K 11 -X 2 -E 3 -G -S 0.95 -H 5 -z -D -t 16 > GRCh38-MHC-haps.vg
```

I get a new graph with more nodes and edges, but also several warnings:
```
[xg] warning: graph does not have edge from 3- to 5+ for path 6
[xg] warning: graph does not have edge from 5- to 6+ for path 6
[xg] warning: graph does not have edge from 10- to 12+ for path 6
[xg] warning: graph does not have edge from 17- to 19+ for path 6
[xg] warning: graph does not have edge from 20- to 21+ for path 6
...
[xg] warning: graph does not have edge from 594871- to 594872+ for path 6
[xg] warning: graph does not have edge from 594872- to 594874+ for path 6
[xg] warning: graph does not have edge from 594874- to 594875+ for path 6
[xg] warning: graph does not have edge from 594875- to 594877+ for path 6
[xg] warning: graph does not have edge from 594877- to 594878+ for path 6
```

I want to clarify these warnings: is this just telling me that GRCh38-MHC-ref.vg did not have an edge from node 3 to node 5 (path 6 being chromosome 6), but with the multiple sequence/graph alignment of the alternate haplotypes, a new edge has been added in GRCh38-MHC-haps.vg? Or is it saying there should be an edge between nodes 3 and 5 to accommodate the new input sequences, but the edge was not able to be incorporated in GRCh38-MHC-haps.vg?

Thanks

**Comment by ekg** [comment] 2016-05-25 18:48
It looks like it is failing during the msga to retain the paths. Remove the
-z flag?

**Comment by hgibling** [comment] 2016-05-25 18:58
I get the same long list of warnings without `-z`

**Comment by ekg** [comment] 2016-05-25 19:01
This warning indicates something is not working correctly. We have included
a path in a previous iteration and it is now not fully embedded in the
graph after editing.

Would it be possible to share the test case inputs in a zip file here?

**Comment by hgibling** [comment] 2016-05-26 01:39
The sequences and vcf are online:
```
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/ALL.chr6.phase3_shapeit2_mvncall_integrated_v3plus_nounphased.rsID.genotypes.GRCh38_dbSNP_no_SVs.vcf.gz
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/ALL.chr6.phase3_shapeit2_mvncall_integrated_v3plus_nounphased.rsID.genotypes.GRCh38_dbSNP_no_SVs.vcf.gz.tbi

wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa

# rename reference sequences to match vcf
sed 's/>chr/>/' GRCh38_full_analysis_set_plus_decoy_hla.fa > GRCh38_full_analysis_set_plus_decoy_hla-no-chr.fa

wget http://hgwdev.sdsc.edu/~anovak/hgvm/hgvm.tar.gz
tar zxvf hgvm.tar.gz
cat hgvm/MHC/ref.fa hgvm/MHC/G*fa > MHC.fa

vg construct -R 6:28510120-33480577 -t 16 -m 32 -v ALL.chr6.phase3_shapeit2_mvncall_integrated_v3plus_nounphased.rsID.genotypes.GRCh38_dbSNP_no_SVs.vcf.gz -r GRCh38_full_analysis_set_plus_decoy_hla-no-chr.fa > GRCh38-MHC-ref.vg
```
Which gives me:
[GRCh38-MHC-ref.vg.zip](https://github.com/vgteam/vg/files/283267/GRCh38-MHC-ref.vg.zip)

```
vg msga -g GRCh38-MHC-ref.vg -f MHC.fa -B 128 -K 11 -X 2 -E 3 -G -S 0.95 -H 5 -z -D -t 16 > GRCh38-MHC-haps.vg
```

I can't compress GRCh38-MHC-haps.vg small enough to add on github, but can send it another way (Dropbox?) if you'd like.

**Comment by hgibling** [comment] 2016-06-14 18:02
Hi,

Wondering if anyone's had a chance to look into what might be going on here.

**Comment by adamnovak** [comment] 2016-06-24 23:39
When you get the final graph, does `vg validate` like it?

I really have no idea what's going on here, beyond the edges needed for the reference path having escaped from the graph somehow; @ekg is the msga person.

I can reproduce this with this tiny starting graph, though. Somehow it tries to make an xg index that has path 6 from the input graph but not the correct nodes/edges for it...

Perhaps we should turn that warning into an error?

[part.vg.zip](https://github.com/vgteam/vg/files/332786/part.vg.zip)

**Comment by hgibling** [comment] 2016-06-26 20:36
> When you get the final graph, does `vg validate` like it?

I get nothing returned to terminal, so... yes I think?

**Comment by ekg** [comment] 2016-06-27 06:02
Yes, no error message means the graph is valid. I'll try to reproduce this
today so we can resolve the bug you ran into. Sorry for the delay.

**Comment by ekg** [comment] 2016-06-27 06:04
We could make it output a positive result. Any suggestions? It doesn't
because Unix convention is "no error, no message".

**Comment by ekg** [comment] 2016-06-27 14:43
Digging back into this. I've been able to construct the graph following the commands and inputs. I think the warnings are somehow related to feeding in a graph generated by `vg construct`, but I'm not yet sure exactly why. I suspect that it's possible to work around this cleanly by stripping the path out of the graph produced from the VCF by `vg mod -D GRCh38-MHC-ref.vg >GRCh38-MHC-ref.nopath.vg` and then putting this into the same `vg msga` command. In the end we map the reference path into the graph as part of the progressive assembly process, so we can drop it up front without issue. I'm trying this now to verify that it checks out.

**Comment by ekg** [comment] 2016-06-27 14:44
Also, I find the graph that is generated to be valid at least as far as `vg validate` knows, which makes the warnings all the more mysterious.

**Comment by hgibling** [comment] 2016-06-29 13:38
> We could make it output a positive result. Any suggestions? It doesn't
because Unix convention is "no error, no message".

Any sort of "graph checks out fine" would be helpful :) 

> I think the warnings are somehow related to feeding in a graph generated by vg construct, but I'm not yet sure exactly why.

I've been able to do a `vg construct` and feed that into `vg msga -g` for a small toy example without issues, but yeah it doesn't seem to like this particular graph.

> I suspect that it's possible to work around this cleanly by stripping the path out of the graph produced from the VCF by vg mod -D GRCh38-MHC-ref.vg >GRCh38-MHC-ref.nopath.vg and then putting this into the same vg msga command. In the end we map the reference path into the graph as part of the progressive assembly process, so we can drop it up front without issue. I'm trying this now to verify that it checks out.

Any luck?

**Comment by ekg** [comment] 2016-06-29 13:54
It did work. I can post it for you or just provide the exact commands. It
seems there is something broken or mismatched with how the path annotations
come out of vg construct. The reference path is embedded in the end as it
is one of the sequences in the MHC.fa, so practically this shouldn't be a
problem.

**Comment by hgibling** [comment] 2016-06-29 14:00
Ooh yay! Commands would be great :)

**Comment by ekg** [comment] 2016-06-29 16:19
@hgibling this is all I've done:

```
time vg mod -D GRCh38-MHC-ref.vg >GRCh38-MHC-ref.nopath.vg
time vg msga -g GRCh38-MHC-ref.nopath.vg -f MHC.fa -B 128 -K 11 -X 2 -E 3 -G -S 0.95 -H 5 -z -D -t 16 > GRCh38-MHC-haps.1.vg
```

No errors are registered. The ref path gets embedded as well as it's in the MHC.fa.

**Comment by ekg** [comment] 2016-06-30 08:59
@hgibling did you have a chance to try this out?

**Comment by hgibling** [comment] 2016-06-30 17:12
Yep, works great. Thanks so much!

**Comment by ekg** [comment] 2016-06-30 17:17
Great! We should still figure out what's different with the construct
result, but this is promising!

Looking forward to what you cook up.

**Comment by adamnovak** [comment] 2016-07-21 17:37
I'm going to close this since the problem seems to be resolved. The construct issue may want its own issue thread.

**Closed by adamnovak** 2016-07-21 17:37 UTC
