### ISSUE TITLE
vg stats -a to evaluate GAM file from vg giraffe went error

### ISSUE THREAD

**Issue by Phonenix233** [vgteam/vg#3914] opened 2023-04-07 07:00 UTC
**1. What were you trying to do?**
I was trying vg stats -a to see the mapping quality of the GAM file from vg giraffe.

**2. What did you want to happen?**
It should turn to the alignment counts or some other things

**3. What actually happened?**
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [vg::io::MessageIterator::operator++] (group 0) message of 1840083539 bytes is too long
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Stack trace path: /tmp/vg_crash_KghrV7/stacktrace.txt
```

**4. If you got a line like `Stack trace path: /somewhere/on/your/computer/stacktrace.txt`, please copy-paste the contents of that file here:**

```
Crash report for vg v1.47.0 "Ostuni"
Stack trace (most recent call last) in thread 4114186:
#13   Object "", at 0xffffffffffffffff, in
#12   Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1f9c072, in __clone
#11   Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x149d568, in start_thread
#10   Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1ed087d, in gomp_thread_start
#9    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0xca362b, in void vg::io::for_each_parallel_impl<vg::Alignment>(std::istream&, std::function<void (vg::Alignment&, vg::Alignment&)> const&, std::function<void (vg::Alignment&)> const&, std::function<bool ()> const&, unsigned long) [clone ._omp_fn.0]
#8    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x5aa989, in vg::io::MessageIterator::take[abi:cxx11]() [clone .cold]
#7    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1ee1279, in _Unwind_Resume
#6    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1ee088a, in _Unwind_RaiseException_Phase2
#5    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1e1f293, in __gxx_personality_v0
#4    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1ebe378, in __cxa_call_terminate
#3    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x1e1f8db, in __cxxabiv1::__terminate(void (*)())
#2    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x5bc60a, in __gnu_cxx::__verbose_terminate_handler() [clone .cold]
#1    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x5befa7, in abort
#0    Object "/data/yxzhu/software/cactus-bin-v2.5.0/bin/vg", at 0x14a0deb, in raise
```

**5. What data and command can the vg dev team use to make the problem happen?**
I think it's because of the GAM file's header which says
```
warning[vg::giraffe]: Refusing to perform too-large rescue alignment of 150 bp against 13058 bp ordered subgraph for read A00920:921:HYHLCDSX2:4:1101:1452:13495 which would use more than 1572864 cells and might exhaust Dozeu's allocator; suppressing further warnings
```

**6. What does running `vg version` say?**

```
vg version v1.47.0 "Ostuni"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```
Thanks you

**Comment by glennhickey** [comment] 2023-04-07 12:51
Out of curiosity: how long are your reads?  Protobuf (and therefore GAM) has a built-in size limit. We've cranked it way up in vg but you're apparently hitting it here with your 1.8gb mapping.  

The only way I know of getting around this is working with GAF instead of GAM, but it looks like `vg stats -a` is one of the few tools left that doesn't support it. So I think fixing that may be the most straightforward way of resolving this issue...

**Comment by jltsiren** [comment] 2023-04-07 20:43
Is the warning message in the GAM file?

If so, then the issue is probably related to your environment. Giraffe prints status messages to stderr and writes the alignments to stdout. If the messages end up in the GAM file, your environment somehow redirects stderr to stdout. In order to use Giraffe properly, you have to prevent it from doing that.

**Comment by Phonenix233** [comment] 2023-04-09 07:35
> Is the warning message in the GAM file?
> 
> If so, then the issue is probably related to your environment. Giraffe prints status messages to stderr and writes the alignments to stdout. If the messages end up in the GAM file, your environment somehow redirects stderr to stdout. In order to use Giraffe properly, you have to prevent it from doing that.

Oh yes, I just noticed stderr was redirected to stdout. I will try to solve by directing stderr to log file. 
Thanks a lot!

**Comment by Phonenix233** [comment] 2023-04-09 07:37
> Out of curiosity: how long are your reads? Protobuf (and therefore GAM) has a built-in size limit. We've cranked it way up in vg but you're apparently hitting it here with your 1.8gb mapping.
> 
> The only way I know of getting around this is working with GAF instead of GAM, but it looks like `vg stats -a` is one of the few tools left that doesn't support it. So I think fixing that may be the most straightforward way of resolving this issue...

The read length are 150bp by illumina next generation sequencing.

**Closed** 2023-04-10 05:22 UTC
