### ISSUE TITLE
I have a question while using vg

### ISSUE THREAD

**Issue by pioneer-pi** [vgteam/vg#4262] opened 2024-04-03 13:05 UTC
Now If I want to execute vg's special format files like .vg,.snarls,.gam and so on. How can I read it directly to python with out transfer the special format to normal format(like json or txt)

Thank you!

**Comment by adamnovak** [comment] 2024-04-08 20:15
I'm going to close this as a duplicate of #4261.

**Closed by adamnovak** 2024-04-08 20:15 UTC
