### ISSUE TITLE
`view vg -dn` works, but other flags result in corrupt *svg files

### ISSUE THREAD

**Issue by evanbiederstedt** [vgteam/vg#1570] opened 2018-03-26 21:17 UTC
It's possible this is a fixed issue, as this version of vg was installed February 2018. I will follow up shortly. 

I have a *vg created using the standard template, without pruning or haplotyping:

```
vg construct -r small/x.fa -v small/x.vcf.gz > x.vg
vg index -x x.xg -g x.gcsa -k 16 x.vg
```

So, I would like to visualize this, following: https://github.com/vgteam/vg/wiki/visualization

This command works, and the resulting *svg file is valid/can be viewed:

`vg view -dn  x.vg | dot -Tsvg -o test_dn.svg
`

It's odd that the same commands for me fail for `-dp`, `-dw`,  and `-dpn`.

```
$ vg view -dp x.vg | dot -Tsvg -o test_dp.svg

Warning: UTF8 codes > 3 bytes are not currently supported (graph graphname) - treated as Latin-1. Perhaps "-Gcharset=latin1" is needed?

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

(process:176621): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()

.....
```

The resulting *svg has errors, see the attached file:
`
error on line 9550 at column 106: Encoding error`

It appears I cannot attach XML files here, so I could e-mail this. Also, as I cannot reproduce the example here, I'm happy to share the *vg's. Perhaps there are troubleshooting tips?

**Comment by adamnovak** [comment] 2018-03-27 23:19
This is probably caused by an outdated Graphviz.

The dot files that vg generates are UTF-8 encoded and contain emoji characters (which are encoded as 4 bytes each), which are used as visually distinct, compact symbols to label paths in the graph. If you con't include paths, everything is fine, but if you do include paths, the emoji will be output. Here's an xxd dump of vg trying to use a saxaphone emoji (🎷):

```
002cba0: 6e77 2c63 6f6c 6f72 3d22 2f64 6172 6b32  nw,color="/dark2
002cbb0: 382f 3822 2c6c 6162 656c 3d22 2020 2020  8/8",label="    
002cbc0: 20f0 9f8e b720 2020 2020 222c 666f 6e74   ....     ",font
002cbd0: 636f 6c6f 723d 222f 6461 726b 3238 2f38  color="/dark28/8
002cbe0: 222c 636f 6e73 7472 6169 6e74 3d66 616c  ",constraint=fal
```

Older versions of Graphviz could not encode these characters as entities in SVG:

https://github.com/ekoontz/graphviz/blob/bd0b15afaccc1a44c1e845724ada732a8f3a8aba/lib/common/utils.c#L1436

However, Graphviz has handled them just fine for at least a couple years now. I can confirm that the dot files vg outputs work with my 2016-vintage Graphviz 2.39:

```
[anovak@kolossus vg]$ dot -V
dot - graphviz version 2.39.20160421.1604 (20160421.1604)
```

**Comment by adamnovak** [comment] 2018-03-27 23:21
I'm going to close this because I really think this is the problem. Please re-open it if updating Graphviz does not work.

**Closed by adamnovak** 2018-03-27 23:21 UTC

**Comment by evanbiederstedt** [comment] 2018-03-28 00:47
Hi @adamnovak 

```
$ dot -V
dot - graphviz version 2.30.1 (20150306.0020)
```

You may have a point.

**Comment by evanbiederstedt** [comment] 2018-03-29 19:58
@adamnovak I can confirm. You're correct. These commands work with 

`dot - graphviz version 2.40.1`
