### ISSUE TITLE
Giraffe crashes with an assertion failure inside longest_detectable_gap, called by get_tail_forest

### ISSUE THREAD

**Issue by Ganxiancai** [vgteam/vg#4081] opened 2023-09-10 17:41 UTC
i constructed a graph-pan genome by minigraph-cactus and get the basic document，then，I want to map paired reads generated by Illumina company in FASTQ format to the graph. i meet error like below

my code
`vg giraffe -Z graphpan.gbz -m graphpan.d2.min -d graphpan.d2.dist -f C34_HQ_R1.fq -f C34_HQ_R2.fq  > C34_unsorted.gam`

error
```
Crash report for vg v1.50.1 "Monopoli"
Stack trace (most recent call last) in thread 6922:
#20   Object "", at 0xffffffffffffffff, in 
#19   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x21472f3, in __clone
#18   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x20a09ba, in start_thread
#17   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x204329d, in gomp_thread_start
#16   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0xeb2e45, in unsigned long vg::io::paired_for_each_parallel_after_wait(std::function, std::function, std::function, unsigned long) [clone ._omp_fn.0]
#15   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0xd1dcf1, in std::_Function_handler::_M_invoke(std::_Any_data const&, vg::Alignment&, vg::Alignment&)
#14   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x116b9ec, in vg::MinimizerMapper::map_paired(vg::Alignment&, vg::Alignment&, std::vector, std::allocator > >&)
#13   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x1160f15, in vg::MinimizerMapper::map_from_extensions(vg::Alignment&)
#12   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x115e104, in void vg::MinimizerMapper::process_until_threshold_b(std::vector > const&, double, unsigned long, unsigned long, vg::LazyRNG&, std::function const&, std::function const&, std::function const&) const [clone .isra.0]
#11   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x1170d77, in vg::MinimizerMapper::map_from_extensions(vg::Alignment&)::{lambda(unsigned long)#8}::operator()(unsigned long) const
#10   Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x116ebbc, in vg::MinimizerMapper::find_optimal_tail_alignments(vg::Alignment const&, std::vector > const&, vg::LazyRNG&, vg::Alignment&, vg::Alignment&) const
#9    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x115e4c9, in void vg::MinimizerMapper::process_until_threshold_c(unsigned long, std::function const&, std::function const&, double, unsigned long, unsigned long, vg::LazyRNG&, std::function const&, std::function const&, std::function const&) const [clone .isra.0]
#8    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x1173c75, in vg::MinimizerMapper::find_optimal_tail_alignments(vg::Alignment const&, std::vector > const&, vg::LazyRNG&, vg::Alignment&, vg::Alignment&) const::{lambda(unsigned long)#2}::operator()(unsigned long) const
#7    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x117319c, in vg::MinimizerMapper::get_tail_forest(vg::GaplessExtension const&, unsigned long, bool, unsigned long*) const
#6    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0xe9db40, in vg::GSSWAligner::longest_detectable_gap(unsigned long, unsigned long) const
#5    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0xe962b4, in vg::GSSWAligner::longest_detectable_gap(unsigned long, unsigned long) const [clone .part.0]
#4    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x206f1c5, in __assert_fail
#3    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x5e5053, in __assert_fail_base.cold
#2    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x5e512b, in abort
#1    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x20757d5, in raise
#0    Object "/share/home/yzbsl_caigx/miniconda3/envs/cactus/bin/vg", at 0x20a21dc, in __pthread_kill
ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
Please include this entire error log in your bug report!
```

 What are the possible reasons? Looking forward to your reply. Thank you！！！

**Comment by adamnovak** [comment] 2023-09-18 17:51
It looks like we're trying to align the "tail" part of a read outside the seed, and we're unable to compute how long of a gap we need to be able to account for because we think the tail is longer than the read is.

That can't possibly be true, but I'm not sure how we're getting that idea.

Would it be possible for you to share your data so we can replicate this problem?

**Comment by Ganxiancai** [comment] 2023-09-21 10:39
Thank you very much for your reply！I fixed the error.

I fixed the error. This error is because I used graph.gbz from the minigraph-cactus output file. I should have used graph.d2.gbz instead

**Comment by adamnovak** [comment] 2023-09-21 15:07
OK, so it looks like this can be caused by a mismatch between the graph file and the minimizer/distance indexes.

We should consider working out a scheme for deciding when we load the files if they actually all go together or not.

I'm going to close this out.

**Closed by adamnovak** 2023-09-21 15:07 UTC
