### ISSUE TITLE
pack table, pack edge table and gaf coverages do not match pack and gam

### ISSUE THREAD

**Issue by brianabernathy** [vgteam/vg#3873] opened 2023-03-02 20:27 UTC
I'm using v1.46.0 to run through giraffe, pack and call processing. This produces the simple SNP below with GT:AD = 0:26,0
`
lg1	11329	>5446442>5446445	C	T	600.712	PASS	AT=>5446442>5446443>5446445,>5446442>5446444>5446445;DP=26	GT:DP:AD:GL:GQ:GP:XD:MAD	0:26:26,0:-2.603835,-62.374147:256:-0.693147:14.982548:26`

However, the relevant pack edge table records below indicate GT:AD = 1:3,14.
```
from.id from.start  to.id   to.end  coverage
5446442 0   5446443 0   3
5446442 0   5446444 0   14
5446443 0   5446445 0   3
5446444 0   5446445 0   14
```

The pack table records also show nodes 5446443 and 5446444 with 3 and 14 coverage. Also, no node 5446442-5446445 offset/position coverages are >= 26.
```
seq.pos	node.id	node.offset	coverage
<records above trimmed>
33852742	5446442	81	17
33852743	5446442	82	17
33852744	5446442	83	17
33852745	5446442	84	17

115837410	5446443	0	3

285560824	5446444	0	14

278016649	5446445	0	18
278016650	5446445	1	17
278016651	5446445	2	16
278016652	5446445	3	17
<records below trimmed>
```

I tried converting the gam to gaf and again counted 3 node 5446443 alignments and 14 node 5446444 alignments. Alignments can be provided if desired, I'm leaving them out for brevity.

However, if I load the region into sequenceTubeMap, 26 reads pass through node 5446443 while no reads pass through node 5446444. This corresponds to the vg call GT:AD = 0:26,0. There seems to be a discrepancy between the binary (gam, pack) files and the text equivalents (gaf, pack table, pack edge table).
![stm snp](https://user-images.githubusercontent.com/58738973/222542257-8803c56f-6377-4d2f-aeac-08d66424a566.png)

**Comment by brianabernathy** [comment] 2023-03-02 20:31
I've checked the pack edge tables produced with several vg versions going back to v1.29.0. All produce the 3,14 coverages seen in the v1.46.0 tools above.

**Comment by brianabernathy** [comment] 2023-03-06 16:17
I've checked a vg call vcf containing ~4M variants. Of the ~4M variants, ~80% contained either a GT **or** AD mismatch based on vg pack edge table data. (~67% had GT mismatches, ~64% had AD mismatches and ~51% had GT **and** AD mismatches) This seems to be a significant problem for anyone relying on pack edge tables (or pack tables, or gafs) for their processing.

**Comment by glennhickey** [comment] 2023-03-06 16:38
If it's huge, perhaps using `vg chunk` to pull out the relevant part of a graph and gam?

**Comment by brianabernathy** [comment] 2023-03-06 17:12
I'll work on chunking the relevant region and checking to be sure the binary vs text discrepancies still exist in the subset. Do you have an email I can send a link and authentication info to?

**Comment by glennhickey** [comment] 2023-03-06 17:34
My github name at gmail will work.  Thanks!

**Comment by brianabernathy** [comment] 2023-03-06 18:52
message sent...

**Comment by glennhickey** [comment] 2023-03-07 03:04
Sorry, I cannot reproduce.

```
vg version
vg version v1.45.0 "Alpicella"
Compiled with g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 on Linux
Linked against libstd++ 20210601
Built by anovak@octagon
```

I extract a subgraph around the variant `>5446442>5446445` 
```
vg chunk -x apis.8.gbz -a apis.8.cerana.50M.mq60.sort.gam -g -r 5446442:5446445 -c 100 -b chunk > chunk.vg
mv chunk_0_ids_5446287_5446600.gam chunk.gam
vg pack -x chunk.vg -g chunk.gam -Q 5 -o chunk.pack
vg pack -x chunk.vg -i chunk.pack -d > chunk.nodepack
vg pack -x chunk.vg -i chunk.pack -D > chunk.edgepack
vg call chunk.vg -k chunk.pack > chunk.vcf
```
The coverage from the pack tables seems consistent with what you show. 
```
grep 5446444 chunk.nodepack
3517    5446444 0       14

5446444 0       5446445 0       14
5446442 0       5446444 0       14
```

And the variant from vg call seems consistent with the pack table with `AD=3,14`
```
grep 5446444 chunk.vcf
lg16    6955284 >5446442>5446445        C       T       271.673 PASS    AT=>5446442>5446443>5446445,>5446442>5446444>5446445;DP=17      GT:DP:AD:GL:GQ:GP:XD:MAD        1/0:17:3,14:-30.737488,-4.048778,-6.506705:24:-1.102090:25.585133:3
```

**Comment by brianabernathy** [comment] 2023-03-07 14:10
Interesting, the differences I notice are your vg version (I was using v1.46.0), chunking vs processing whole graph/gam and the position (CHROM/POS) of the target variant. Perhaps chunking is removing the data causing problems. Also odd that the position of the variant moved from lg1 11329 to lg16 6955284 in your chunk test. Any thoughts on why that would occur?

Here are the steps I took to produce the conflicting vg call variant.
```
vg pack -x apis.8.gbz -g apis.8.cerana.50M.mq60.sort.gam -o test.pack
vg call -a -d 1 -r apis.8.snarls -k test.pack apis.8.gbz > test.vcf
```

I'll post the snarls and send you another email with details...

**Comment by brianabernathy** [comment] 2023-03-07 18:29
No problem, I hope you are able to track down and squash this bug soon!

**Comment by glennhickey** [comment] 2023-03-07 20:39
Wait a second, it's not the coverages that are different, it's the node ids.  

When going from GFA->GBZ, some nodes get chopped up because GBZ can't handle lengths > 1024. The GBZ file itself keeps around a mapping back to the old unchopped GFA ids. Some tools use this mappings to make the node chopping "transparent".  I think a round-trip via `vg convert` would revert back to the unchopped nodes for example.

`vg deconstruct` and `vg call` both use the mapping when filling out the VCF -- so the various id's will be in terms of the original unchopped graph in the GFA (from which the GBZ was derived).  

but the table from `vg pack` is referring directly to the chopped id's in the GBZ.   You can see the id translation table (which maps from unchopped gfa id space (col 2) to chopped gbz id space (col 3) with
```
vg gbwt -Z apis.8.gbz --translation apis.8.trans
```
Then searching for the nodes from the variant we were looking at 
```
T       5446443 5463125
T       5446444 5463126
```
And looking at their coverages in the pack file
```
vg pack -i test.pack -d -n 5463125 -n 5463126 -n 5446443 -n 5446444 -x apis.8.gbz  
seq.pos node.id node.offset     coverage
32923149        5463126 0       0
115837410       5446443 0       3
221210766       5463125 0       26
285560824       5446444 0       14
```
So even though your VCF is showing the site in terms of node 5446443,5446444 the GBZ/PACK file are internally using the chopped coordinate space of 5463125,5463126.

I (and I'm sure many others) have wasted so much time forgetting all this and, like right here, going off track when trying to link back the VCF to the chopped GBZ graph.  I've been tempted to just chop everything down at the outset so the gfa and gbwt would be consistent, but have held back as that would hinder non-vg tools (like bandage).  

What I will do for now is add an option to call (maybe making it default?) to not bother with the id mapping.  that was how it used to behave when using xg/gbwt before we recently switched to vg.  Same thing for deconstruct.

**Comment by brianabernathy** [comment] 2023-03-07 21:34
I recall reading somewhere (minigraph-cactus issue?) that gbz node lengths were limited to 1024 while the gfa was left "unchopped", but didn't know if/how the unchopped gfa and chopped gbz coordinates were being stored, referenced or printed. Thanks for providing detail to clarify their lookup and usage. I follow your approach but agree that juggling mutliple coordinate systems is a bit chaotic and confusing.

After running minigraph-cactus I may prefer to have a gfa and gbz with matching node ids. You seem to indicate that running `vg convert -f gbz > chopped.gfa` will result in an unchopped gfa. Is the preferred approach (the one that minigraph-cactus uses?) to `vg mod -X 1024 gfa > chopped.gfa`?

**Comment by glennhickey** [comment] 2023-03-08 14:44
minigraph-cactus does the chopping by way of `vg gbwt` when converting the unchopped GFA into the chopped GBWT (from which all subsequent VG indexes are based).  I guess this is the preferred way, as it keeps the translation around in the GBZ in case you need it later (hah).  

If you want a GFA that is exactly consistent with the GBZ you can run
```
vg convert -f graph.gbz --vg-algorithm > graph.gfa
```
If you run the same command without the `--vg-algorithm` option you will end up with an unchopped GFA (which should be identical to the one you get from `--gfa` in miningraph-cactus).

In the next release of `vg`,  `vg call` and `vg deconstruct` will switch to using chopped ID's by default for GBZ inputs (unchopped toggled on with `-O`).  #3879 

Minigraph-Cactus will keep writing VCFs with unchopped IDs by default but there will be an option in the next release to use chopped instead https://github.com/ComparativeGenomicsToolkit/cactus/pull/950. I'll also add some notes to the documentation about all this...

I think these options and commands will let a (determined) user work in the ID space they want, though there's definitely still room for improvement.

**Closed** 2023-03-08 14:50 UTC
