### ISSUE TITLE
Handling inexact overlaps in string graph

### ISSUE THREAD

**Issue by shilpagarg** [vgteam/vg#1607] opened 2018-04-06 12:22 UTC
Here is one test example, that we want to fix in terms of handing overlaps. We don't want to skip this edge because the overlap doesn’t represent exact match, and it’s set based on 00195046 (the successor) which has a length of 16669 bp.

https://transfer.sh/tAGhU/testexample.gfa

Also, we want to create bubbles from these inexact matches, which is not handled in the current bluntification implementation.

**Comment by adamnovak** [comment] 2018-04-06 18:06
My understanding of the issue is:

When there is an overlap specified in the GFA, and the overlapping sequences are not exact matches, right now vg just arbitrarily takes one of the two to represent the overlapped region, discarding the sequence of the other. This is even worse when multiple things overlap transitively with non-exact matches, in which case only one sequence represents everything.

What we want is for the overlapping sequences to be aligned to each other, and for that alignment to turn into a graph.

So if we have a GFA that says that `GATTACA` and `TAAAGGG` overlap by 4 bases, we currently get `GAT-TACA-GGG`, and we want to get `GAT-TA-(C/A)-A-GGG`.

The other aspect here I think is overlaps longer than the node length. Right now we arbitrarily shorten them to the length of the shortest involved node, but I *think* what the assembler is trying to say is that the shorter node is actually contained within the longer node. So right now if we have `ATT` and `CATTAG` overlapping by 4 bases, we would generate (arbitrarily picking a sequence for overlaps) `ATT-TAG`, but we should be generating `C-ATT-AG`.

**Comment by ekg** [comment] 2018-04-09 12:55
This is all correct. The key issue is that the bluntification algorithm relies on an exact match at the end of the alignment. This is not really expected in any case other than high depth Illumina based string graphs. In order to operate at all I have reduced the model to greedily take the first sequence as the overlap sequence. The information loss is not permanent because we can realign the reads to the graph and correct the errors and bubble losses that are introduced this way. @shilpagarg have you considered doing this? I would be happy to help. @adamnovak may have a different idea, but this seems much easier than resolving the bluntification problem in the generic overlap alignment sense.

In the long term I would like to take the overlap graph (as specified in PAF or potentially GFA) and reduce this into a regular, overlap-free graph. This would be a S and L based graph in GFA, with aligned sequences represented in P paths. Doing this efficiently for large graphs appears to be a serious challenge due to memory constraints. (Every base in every read needs to be recorded along with its mappings to other bases.) On the other hand, it is mathematically clean, in that it's a simple compression of a given overlap set. No existing methods provide this and it would be of great use to people like us who want to decouple various assembly steps. This need not live directly in vg, as it reads PAF/GFA and writes GFA.

**Comment by ekg** [comment] 2018-04-09 12:56
CC @richarddurbin as this may be of interest. We have discussed the "squish graph" model for PAF reduction.

**Comment by adamnovak** [comment] 2018-04-09 17:35
Realigning the reads against the graph to restore the sequences that were discarded doesn't sound like the right approach to me. It's a lot of work to align all the reads, there's no guarantee that vg will put them where the assembler put them, and you might not have the read set that was used to generate the assembly you imported. Plus you need logic to tell the difference between read errors and differences that have enough support to become bubbles, and that logic might not match what the assembler used when it decided that two overlapping sequences should have different base calls.

Realigning the assembly *contigs* might work better, but it's still a lot of work to recover information that you had easy access to at the import step.

The current behavior of arbitrarily resolving things is probably something we want to keep around, but it would also be good to have a more faithful way of importing GFA without throwing away so much data.

At the very least, I think we have to change the arbitrary rewriting of longer-than-the-node-length overlaps. I don't *really* know what the assembler is trying to say when it emits those, but I suspect that just clipping them to the length of the sequence (and arbitrarily shifting the alignment by many columns), followed by arbitrarily picking one sequence to represent the aligned block, risks producing graphs that are quite different than what the assembler had in mind.

**Comment by shilpagarg** [comment] 2018-04-09 18:01
@ekg: Adam and I discussed this issue to fix it without losing any information for downstream steps. Adam has implemented the previous version, so he knows the code in detail. Please give us some time to do it.

**Comment by ekg** [comment] 2018-04-11 08:54
There is absolutely a way to resolve this without information loss, but it requires that the size of the components in the overlap nets be limited or we could risk memory exhaustion and extremely high runtimes to resolve the overlaps.

It is awkward if the assembler is producing approximate descriptions of the overlaps, as we'd have to realign everything. But, if the assembler produces correct output with fully specified cigars then it is possible to directly build up the graph base by base. If the region that needs to be reduced is small then we can probably implement this without too much concern for memory usage. However, in repeats or regions where many reads are collapsing together an implementation using vg's C++ data model may start to push the limits of the systems we're working on.

I think this is worth focusing on because of the information loss that all assemblers force us to incur. In practice they seem to be generating chopped up graphs that don't match the expected hairball form with a single giant component. I assume this is due to repeat cleaning that is in vogue now. If we could work directly on the mutual alignment object then we would preserve even more information downstream.

**Comment by adamnovak** [comment] 2018-04-11 17:55
Hm. I forgot about the CIGARs. If we can rely on those we don't have to do
any alignment at all.

**Comment by adamnovak** [comment] 2018-04-13 23:10
OK, I've set down a spec for what I think a GFA import ought to look like:

https://github.com/vgteam/vg/compare/vgteam:master...adamnovak:gfa-import

I want to get rid of the trip through the VG schema between GFA read and the bluntification step. The GFA schema can't hold the edge overlap alignments, and I don't think it really makes sense to add them in. Instead, I want to go straight from GFA through handle graphs to blunt graph in one `vg::algorithms` function.

Then I should be able to just read the CIGAR and do the pinching for all the edges more or less in one pass, and then dump from pinch graph into VG graph. I can also have a flag for not bothering with all of that, and just arbitrarily resolving the CIGAR Ms and doing something sensible with any other not-all-M alignments. (That might mean discarding those edges; right now we just abut connected sequences with no merging when the alignment isn't all M.)

I also might want to be adding path support to the handle API to make this work, because all the algorithms are supposed to use the handle API.

**Comment by shilpagarg** [comment] 2018-04-13 23:16
Thanks. This sounds good. Also, I am not sure if all the assemblers report
this CIGAR string.

**Comment by ekg** [comment] 2018-04-15 08:01
As far as I know the GFA format does allow for the recording of the
alignment. In GFA2 there are multiple ways to do it.

**Closed as completed** 2018-07-13 22:27 UTC

**Comment by adamnovak** [comment] 2018-07-13 22:31
I've merged in code that interprets the CIGARs during GFA import. It doesn't handle past-the-node-length overlaps or second-guess the alignment, but I suspect it will work well for well-behaved GFA files.
